/**
 * Collab Circles — invite links. A code is 43 base64url characters (244 random bits, generated by the
 * database); the link is `/circles/join/<code>`.
 */
export const INVITE_CODE = /^[A-Za-z0-9_-]{43}$/

export const JOIN_PATH = "/circles/join/"

export function isInviteCode(value: string): boolean {
  return INVITE_CODE.test(value)
}

/** The join link for a code, on `origin` (e.g. `https://orbi.app`). */
export function inviteLink(origin: string, code: string): string {
  return `${origin.replace(/\/+$/, "")}${JOIN_PATH}${code}`
}

/**
 * The code from whatever was pasted: the link (any origin, with or without a trailing slash, query or
 * hash), the path, or the bare code. Null when there's no valid code in it.
 */
export function parseInvite(input: string): string | null {
  const value = input.trim()
  if (!value) return null
  if (isInviteCode(value)) return value
  const match = /\/circles\/join\/([A-Za-z0-9_-]+)/.exec(value)
  if (!match) return null
  return isInviteCode(match[1]) ? match[1] : null
}
