/**
 * Onboarding copy — English. `copy-tl.ts` mirrors every key in natural Taglish (the type forces it).
 * Technical terms (pillars, niche, leads, content…) stay English in both, the way Filipino creators say them.
 */
const plural = (n: number, one: string, many: string) => (n === 1 ? one : many)

export const EN = {
  lang: { english: "English", taglish: "Taglish", label: "Language" },
  common: {
    continue: "Continue",
    back: "Back",
    toContinue: "to continue",
    stepOf: (n: number, total: number) => `Step ${n} of ${total}`,
    setup: "Setup",
    quickSetup: "Quick setup",
    detailedSetup: "Detailed setup",
    nicheSetup: "Niche Discovery",
    exitSetup: "Exit setup",
    optional: "Optional",
    required: "required",
    edit: "Edit",
    cancel: "Cancel",
    add: "Add",
    progress: "Setup progress",
    stepAria: (n: number, label: string, state: "done" | "current" | "") => `Step ${n}: ${label}${state === "done" ? ", done" : state === "current" ? ", current" : ""}`,
    srStep: (n: number, total: number, title: string) => `Step ${n} of ${total}: ${title}`,
    /** The Quick setup progress: "2 of 4". */
    progressOf: (n: number, total: number) => `${n} of ${total}`,
    upTo: (n: number) => `Up to ${n}.`,
    picked: (n: number) => `${n} picked`,
    remove: (name: string) => `Remove ${name}`,
  },
  phases: { discovery: "Niche Discovery", setup: "Set up Orbi" },
  steps: {
    start: {
      short: "Start",
      title: "Let's start",
      description: "Your name and where you post. Orbi builds the rest from your answers.",
    },
    about: {
      short: "About you",
      title: "About you",
      description: "What you love talking about and what you're good at. Tap what fits — type anything that's missing.",
    },
    who: {
      short: "Who you help",
      title: "Who you help",
      description: "The people your content is for, and what your brand should do for you.",
    },
    pick: {
      short: "Your niche",
      title: "Pick your niche",
      description: "Three directions built from your answers. Tap the one that feels most like you — or write your own.",
    },
    welcome: {
      short: "Start",
      title: "Let's find your niche first",
      description: "Before any content, we figure out what you should be known for — from what you love, what you're good at and who you want to help.",
    },
    hilig: {
      short: "Interests",
      title: "What could you talk about for hours?",
      description: "Topics you'd follow and talk about even if nobody paid you. Pick at least two.",
    },
    galing: {
      short: "Skills",
      title: "What are you good at?",
      description: "Skills people already trust you with — and the proof. Specific beats impressive.",
    },
    kanino: {
      short: "Audience",
      title: "Who do you want to help?",
      description: "The people your content is really for: where they are now and what they struggle with.",
    },
    para_saan: {
      short: "Goals",
      title: "What should your brand do for you?",
      description: "Clients, a better career, an audience, products… This shapes your goals and how your niche earns.",
    },
    niche: {
      short: "Niche",
      title: "Pick your niche",
      description: "Three directions built from your answers. Compare them, pick one and make it yours — or write your own.",
    },
    identity: {
      short: "You",
      title: "The basics about you",
      description: "Your name and role — every idea, hook and script is written from here.",
    },
    platforms: {
      short: "Platforms",
      title: "Where will you show up?",
      description: "Your platforms, how often you'll post and your weekly schedule. A few platforms done consistently beat every platform done occasionally.",
    },
    voice: {
      short: "Voice",
      title: "How do you sound?",
      description: "Language, tone and style. The Content Strategist and every AI draft follow these choices.",
    },
    pillars: {
      short: "Pillars",
      title: "Confirm your content pillars",
      description: "The themes you'll rotate through, from your niche. Edit anything — targets must add up to 100%.",
    },
    strategy: {
      short: "Strategy",
      title: "Your initial strategy",
      description: "Positioning, pillar mix and starter ideas inside your niche. Choose your ideas, then finish setup.",
    },
  },
  welcome: {
    chooseLanguage: "Choose your language",
    languageHint: "Switch anytime from the top bar — suggestions come back in the language you pick.",
    englishHint: "Clear, simple English",
    taglishHint: "English and Tagalog, the way you actually talk",
    how: "How this works",
    flow: [
      { title: "Find your niche", text: "What you love, what you're good at and the people you want to help become three niche directions to compare." },
      { title: "Set up Orbi", text: "Platforms, voice and pillars — pre-filled from the niche you pick." },
      { title: "Get your first ideas", text: "A starting strategy with 30 ideas that fit your niche." },
    ],
    time: "About 10 minutes · saved as you go",
    start: "Start",
  },
  hilig: {
    label: "Your interests",
    description: "Pick from the suggestions or type your own and press Enter.",
    placeholder: "e.g. K-drama, Running, Coffee",
    suggestions: "Suggestions",
    groups: { money: "Money & business", work: "Work & career", digital: "Digital & tech", life: "Life & wellness", hobbies: "Hobbies & creative" },
    count: (n: number) => (n < 2 ? `${n} of 2 minimum` : `${n} picked`),
    test: "Quick test: would you still post about it after 50 posts nobody liked? That's a real interest.",
  },
  galing: {
    skills: "Your skills",
    skillsDescription: "Pick or type what you're good at. Up to 10.",
    skillsPlaceholder: "e.g. Bookkeeping, Video editing, Teaching",
    groups: { business: "Business & operations", marketing: "Marketing & content", tech: "Tech & tools", people: "Teaching & hands-on" },
    help: "What do people ask you for help with?",
    helpPlaceholder: "e.g. How to price their cakes, how to file taxes as a freelancer",
    years: "Years of experience",
    yearsSuffix: "years",
    proof: "Results or proof",
    proofDescription: "Numbers, clients, before-and-afters — anything that shows it works.",
    proofPlaceholder: "e.g. Helped 40+ freelancers register with BIR",
    story: "A short proof story",
    storyDescription: "Optional — saved to your Story Vault and used for your first ideas.",
    storyPlaceholder: "e.g. My first client paid me ₱500 for a logo. Two years later I was running a team of three…",
  },
  kanino: {
    who: "Who do you want to help?",
    whoDescription: "Pick or type one or more. The first becomes your primary persona.",
    whoPlaceholder: "e.g. Home bakers, New nurses, Online sellers",
    stage: "Where are they now?",
    stagePlaceholder: "e.g. First year freelancing, no idea about taxes yet",
    level: "Their level",
    levels: { Beginner: "Beginner", Intermediate: "Intermediate", Advanced: "Advanced", Mixed: "Mixed levels" },
    goal: "Where do they want to be?",
    goalPlaceholder: "e.g. Earn from baking without working for free",
    problems: "Their problems",
    problemsDescription: "In their own words, most painful first. Three or more makes your niche sharp.",
    problemsPlaceholder: "e.g. Doesn't know how to file taxes",
    addProblem: "Add problem",
    problemsHint: (n: number) => (n >= 3 ? "Good — that's enough to build a niche on." : `Add ${3 - n} more for a sharper niche.`),
    platforms: "Where they spend time",
    platformsDescription: "We'll suggest these as your platforms later.",
  },
  paraSaan: {
    aims: "Pick up to 3",
    aimsDescription: "What should all this content lead to?",
    options: {
      clients: { title: "Get clients", text: "Freelance, consulting or services" },
      career: { title: "Grow my career", text: "A better job, a promotion or a switch" },
      audience: { title: "Build an audience", text: "Reach and influence" },
      products: { title: "Sell products", text: "Templates, courses, merch" },
      speaking: { title: "Speaking & collabs", text: "Talks, media, partnerships" },
      community: { title: "Build a community", text: "People who learn together" },
    },
    primary: "Main goal",
    primaryDescription: "Your goals in the app come from your picks. Choose which one leads.",
    targets: "Targets",
    targetsDescription: "What success looks like. Refine them any time in Strategy → Goals.",
    primaryTag: "Primary",
    secondaryTag: "Secondary",
    noTarget: "No target",
    targetAria: (goal: string, metric: string) => `${goal} target (${metric})`,
    periodAria: (goal: string) => `${goal} period`,
  },
  quick: {
    time: "About 3 minutes · saved as you go",
    language: "Language",
    name: "Your name",
    namePlaceholder: "e.g. Maria Santos",
    platforms: "Where do you post?",
    platformsHint: "Pick every platform you use. Orbi plans a weekly posting schedule for them.",
    interests: "What could you talk about for hours?",
    interestsHint: "Tap at least 2, or type your own and press Enter.",
    interestsPlaceholder: "e.g. K-drama, Running, Coffee",
    interestsCount: (n: number) => (n < 2 ? `${n} of 2` : `${n} picked`),
    skills: "What are you good at?",
    skillsHint: "What people already ask you for help with.",
    skillsPlaceholder: "e.g. Bookkeeping, Video editing, Teaching",
    showMore: "Show more",
    showLess: "Show less",
    knowNiche: "I already know my niche",
    knowNicheText: "Already have a niche in mind?",
    audience: "Who do you want to help?",
    audienceHint: "Tap or type at least one. The first becomes your main audience persona.",
    audiencePlaceholder: "e.g. Home bakers, New nurses, Online sellers",
    problem: "Their #1 problem",
    problemHint: "In their own words. Add more anytime in the Problem Bank.",
    problemPlaceholder: "e.g. Doesn't know how to file taxes",
    problemIdeas: (audience: string) => `Common for ${audience}`,
    aims: "What should your brand do for you?",
    aimsHint: "Up to 3. Skip it and Orbi starts with growing an audience.",
    bestMatch: "Best match",
    seeDetails: "See details",
    hideDetails: "Hide details",
    ownTitle: "Write my own",
    ownText: "Already have a niche in mind? Say it in one sentence.",
    ownLabel: "Your niche in one sentence",
    ownPlaceholder: "e.g. Taxes and bookkeeping made simple for new Filipino freelancers",
    ownHint: "Orbi builds your pillars and first ideas from this sentence.",
    ownDescription: "You know your niche — write it below, and Orbi takes it from there.",
    needMore: "Add at least 2 interests and who you help, and Orbi will suggest three directions.",
    findForMe: "Suggest directions instead",
    editLater: "Positioning and pillars follow the niche you pick. Fine-tune them anytime in Brand HQ.",
    choicesAria: "Niche directions",
    building: "Setting up your Orbi",
    buildingText: "Orbi is building your workspace from your answers.",
    items: {
      brand: "Brand profile",
      pillars: "Content pillars",
      schedule: "Posting schedule",
      goals: "Goals",
      ideas: "First ideas",
    },
    pillarsDone: (n: number) => `${n} ${plural(n, "pillar", "pillars")}`,
    scheduleDone: (n: number) => `${n} ${plural(n, "post", "posts")} a week`,
    ideasDone: (n: number) => `${n} ${plural(n, "idea", "ideas")}`,
    failed: "Setup stopped",
    failedHint: "Your answers are saved. Try again, or go back and change something.",
    tryAgain: "Try again",
    backToAnswers: "Back to my answers",
  },
  niche: {
    generating: "Finding three niche directions from your answers…",
    offlineNote: "Built from your answers with offline templates — edit anything.",
    aiNote: "Drafted from your answers — edit anything.",
    regenerate: "Regenerate",
    regenerating: "Regenerating…",
    errorTitle: "Couldn't find niche directions",
    errorHint: "Try again, or write your own niche below — your answers are saved.",
    tryAgain: "Try again",
    notesTitle: "Sharpen these",
    kinds: { expertise: "Expertise-led", passion: "Passion-led", audience: "Audience-led" },
    kindHints: { expertise: "Built on what you're good at", passion: "Built on what you love", audience: "Built on who you help" },
    fit: { passion: "Passion", expertise: "Expertise", demand: "Demand" },
    fitAria: (label: string, score: number) => `${label} ${score} out of 10`,
    audience: "Audience",
    pillars: "Pillars",
    posts: "Sample posts",
    money: "How it can earn",
    why: "Why it fits",
    risk: "Watch out",
    more: "Posts & monetization",
    less: "Hide details",
    choose: "Choose this",
    chosen: "Chosen",
    ownTitle: "Write your own",
    ownText: "Already have a niche in mind? Write it in one sentence.",
    ownButton: "Write my own",
    yours: "Your niche",
    yoursDescription: "One sentence. Edit it until it sounds like you.",
    nicheLabel: "Niche statement",
    nichePlaceholder: "e.g. Taxes and bookkeeping made simple for new Filipino freelancers",
    positioning: "Your positioning",
    positioningDescription: "One sentence your audience could repeat about you.",
    positioningEmpty: "Your positioning statement appears here as you type.",
    leads: { audience: "I help", result: "to", method: "through" },
    hints: { audience: "who you help", result: "the result you help them get", method: "your method" },
    placeholders: { audience: "e.g. new freelancers", result: "e.g. file taxes with confidence", method: "e.g. simple bookkeeping systems" },
    appliedFirst: "Your pillars, positioning and industry now follow this niche.",
    appliedRerun: "Your positioning now follows this niche. Your pillars stay as they are until you change them.",
    replacePillars: (n: number) => `Also replace my pillars with this niche's ${n} pillars`,
    replacePillarsHint: "Current pillars are switched off, never deleted.",
    pickFirst: "Choose a direction above or write your own niche.",
    outOfTen: (n: number) => `${n}/10`,
  },
  clarity: {
    title: "Clarity check",
    description: "Quick checks before you continue — advice, not blockers.",
    waiting: "Runs as soon as you choose or write a niche.",
    allGood: "Clear and specific — ready to set up Orbi.",
    toSharpen: (n: number) => `${n} ${plural(n, "thing", "things")} to sharpen`,
    fix: "Fix",
    items: {
      sentence: { ok: "One clear sentence", warn: "Make it one clear sentence of 4–28 words — no lists." },
      audience: { ok: "A specific audience", warn: "Name a specific audience. “Everyone” is no one." },
      problems: {
        ok: "Enough real audience problems",
        warn: (n: number) => `Add ${3 - n} more real audience ${plural(3 - n, "problem", "problems")} — they're what your content solves.`,
      },
      range: { ok: "Enough topic range for 30 ideas", warn: "Add topics or pillars so 30 ideas won't repeat — aim for 4+ pillars." },
      money: { ok: "A monetization path", warn: "Pick what the brand should do for you so the niche leads somewhere." },
    },
  },
  identity: {
    niche: "Your niche",
    changeNiche: "Change",
    name: "Your name",
    namePlaceholder: "e.g. Maria Santos",
    brandName: "Brand name",
    brandNamePlaceholder: "e.g. Santos Studio",
    brandNameHint: "Leave empty if your brand is simply you.",
    role: "Role",
    rolePlaceholder: "e.g. Freelance bookkeeper",
    industry: "Industry",
    industryPlaceholder: "e.g. Accounting, Food, Education",
    industryHint: "Pre-filled from your niche.",
    location: "Location",
    locationPlaceholder: "e.g. Manila, Philippines",
  },
  platforms: {
    audienceUses: "Your audience spends time on",
    useThese: "Use these",
    group: "Main platforms",
    note: "Chosen platforms get an active platform strategy; the rest stay off until you turn them on in Strategy → Platforms.",
    hints: {
      facebook: "Groups, long posts and community — where most Filipinos already are",
      tiktok: "Short videos with the biggest reach for new creators",
      instagram: "Carousels, Reels and a visual portfolio",
      youtube: "Searchable long videos and Shorts",
      linkedin: "Professionals, B2B and career content",
      x: "Fast takes, threads and industry conversations",
      threads: "Casual text posts and conversations",
    },
  },
  posting: {
    weekly: "Weekly post target",
    weeklyDescription: "One post on one platform counts as one. Change the total or the split — they stay in sync.",
    perWeekLabel: "Posts per week",
    perWeekSuffix: "/ wk",
    perPlatformAria: (platform: string) => `${platform} posts per week`,
    tooMany: "That's two or more posts a day. Start lower and raise it once your content buffer keeps up.",
    schedule: "Posting schedule",
    scheduleDescription: "Recurring weekly slots — your calendar and What-to-post use them.",
    postsPerWeek: (n: number) => `${n} ${plural(n, "post", "posts")} / week`,
    typeAria: "Schedule type",
    modes: {
      recommended: { title: "Recommended weekly strategy", text: "A themed day for each pillar type, adapted to your platforms." },
      custom: { title: "Custom per day", text: "Choose the days, themes, platforms and times yourself." },
    },
    recommendedAria: "Recommended weekly schedule",
    customAria: "Custom weekly schedule",
    noPost: "No post",
    themePlaceholder: "Theme, e.g. Tutorial",
    postOn: (day: string) => `Post on ${day}`,
    themeAria: (day: string) => `${day} theme`,
    platformsAria: (day: string) => `${day} platforms`,
    timeAria: (day: string) => `${day} time`,
  },
  voice: {
    language: "Language",
    languageNotes: {
      english: "Clear, conversational English.",
      tagalog: "Natural Filipino — the way you'd explain it to a friend.",
      taglish: "English and Tagalog mixed, the way you actually talk.",
    },
    tone: "Tone",
    toneDescription: (n: number) => `Pick up to ${n}. Picking another replaces the oldest.`,
    personality: "Personality",
    personalityDescription: (n: number) => `Up to ${n} traits people should feel in your content.`,
    cta: "Call-to-action style",
    ctaDescription: "How you usually ask for action at the end of a post.",
    ctaPresetsAria: "CTA style presets",
    ctaPresets: [
      { label: "Soft", text: "Soft by default — comment a keyword to get the resource, or DM me your situation." },
      { label: "Conversation", text: "End with a question people can answer from their own experience." },
      { label: "Direct", text: "Direct on conversion posts only — book a call or grab the offer through the link." },
    ],
    ctaPlaceholder: "Or write your own — e.g. Comment GUIDE and I'll send you the template.",
    rules: "Brand rules",
    rulesDescription: "Optional guardrails every draft follows.",
    always: "Always",
    never: "Never",
    alwaysPlaceholder: "e.g. Use real numbers. Admit what I got wrong.",
    neverPlaceholder: "e.g. Promise overnight results. Name clients.",
  },
  pillars: {
    total: (n: number) => `Total ${n}%`,
    count: (n: number) => `${n} ${plural(n, "pillar", "pillars")}`,
    left: (n: number) => `${n}% left to assign`,
    over: (n: number) => `${n}% over`,
    rebalance: "Rebalance to 100%",
    even: "Split evenly",
    listAria: "Content pillars",
    noDescription: "No description",
    nicheBadge: "Niche",
    customBadge: "Custom",
    targetAria: (name: string) => `${name} target percentage`,
    fromNiche: "Pillars for your niche",
    fromNicheText: "Your chosen niche suggests these pillars.",
    useNiche: "Use these pillars",
    general: "General pillars you can add",
    addCustom: "Add a custom pillar",
    name: "Pillar name",
    namePlaceholder: "e.g. Freelancer Q&A",
    description: "Description",
    descriptionPlaceholder: "e.g. Answering one real question every week",
    addPillar: "Add pillar",
    nameMissing: "Name the pillar.",
    nameTaken: "You already have a pillar with that name.",
    tooMany: (n: number) => `You can choose up to ${n} pillars.`,
    applied: "Niche pillars applied",
  },
  strategy: {
    drafting: "Drafting your positioning, pillar mix and up to 30 starter ideas inside your niche…",
    errorTitle: "Couldn't generate your strategy",
    errorHint: "Try again, or finish setup now and generate ideas later in the Idea Generator — your answers are saved either way.",
    tryAgain: "Try again",
    offlineNote: "Assembled from your answers with offline templates — edit anything.",
    aiNote: "Drafted from your answers — edit anything before you finish.",
    regenerate: "Regenerate",
    regenerating: "Regenerating…",
    outOfDate: "Out of date",
    outOfDateText: "— your answers changed since this strategy was drafted. Regenerate to refresh the ideas.",
    previousDraft: "Your previous draft is still here.",
    niche: "Niche",
    positioning: "Positioning statement",
    positioningEmpty: "Add who you help and the result you deliver in the Niche step.",
    suggested: "Suggested",
    useThis: "Use this",
    editToUse: "Edit the Niche step if you'd like to use this wording.",
    knownFor: "Known for",
    pov: "Point of view",
    povDescription: "Beliefs you'll keep coming back to.",
    povPlaceholder: "What do you believe that others in your space don't?",
    pillars: "Content pillars",
    pillarsDescription: (n: number, total: number) => `${n} pillars · ${total}% total`,
    suggestedMix: "Suggested mix — weighted toward your goals",
    useSuggestedMix: "Use suggested mix",
    ideas: "Initial content ideas",
    ideasCount: (selected: number, total: number) => `${selected} of ${total} selected · saved to your Idea Bank · click a title to edit`,
    selectAll: "Select all",
    clear: "Clear",
    keepIdea: (title: string) => `Keep “${title}”`,
    ideaTitle: "Idea title",
    ideaPillar: (title: string) => `Pillar for “${title}”`,
    noPillar: "No pillar",
    noIdeas: "No ideas in this draft",
    noIdeasText: "Regenerate to get starter ideas grounded in your niche and your audience's problems.",
    willAdd: (n: number) => `${n} ${plural(n, "idea", "ideas")} will be added`,
    toasts: { positioning: "Positioning updated", knownFor: "Known-for updated", pov: "Point of view updated", mix: "Suggested pillar mix applied", undo: "Undo" },
    regenerateConfirm: {
      title: "Regenerate your strategy?",
      changed: "Your answers changed. A new strategy replaces the current ideas, including your title edits, selection and pillar picks.",
      manual: "You'll get a new set of ideas. Your title edits, selection and pillar picks on the current ideas are replaced.",
      confirm: "Regenerate",
    },
  },
  summary: {
    title: "What Finish setup creates",
    description: "Everything is saved to your workspace and stays editable.",
    niche: "Niche",
    brandHq: "Brand HQ",
    brandHqDetail: (who: string) => `${who || "Your profile"} — positioning, voice and brand rules`,
    goal: "Goal",
    goals: "Goals",
    chooseGoal: "Choose a primary goal",
    primary: "Primary",
    secondary: "Secondary",
    pillars: "Content pillars",
    persona: "Primary persona",
    personaDetail: (name: string, n: number) => `${name || "Unnamed"} · ${n} ${plural(n, "problem", "problems")} for your Problem Bank`,
    platforms: "Platforms",
    postsPerWeek: (n: number) => `${n} posts / week`,
    schedule: "Posting schedule",
    scheduleDetail: (n: number, custom: boolean) => `${n} weekly ${plural(n, "slot", "slots")} · ${custom ? "custom" : "recommended strategy"}`,
    ideaBank: "Idea Bank",
    ideaDetail: (n: number) => `${n} starter ${plural(n, "idea", "ideas")}`,
    storyVault: "Story Vault",
    storyDetail: "Your proof story",
    editAria: (title: string) => `Edit ${title}`,
  },
  finish: {
    finish: "Finish setup",
    generate: "Generate my strategy",
    regenerate: "Regenerate strategy",
    review: "Review strategy",
    showNiches: "Show my niche options",
    saveNiche: "Save my niche",
    settingUp: "Setting up your workspace…",
    savingNiche: "Saving your niche…",
    welcome: (name: string) => `Welcome${name ? `, ${name}` : ""} — your workspace is set up`,
    summary: (pillars: number, ideas: number, weekly: number) =>
      `${pillars} pillars${ideas ? `, ${ideas} ideas in your Idea Bank` : ""} and a ${weekly}-post weekly plan are ready.`,
    failed: "Couldn't finish setup",
    attention: "A few answers need attention",
    nicheSaved: "Niche saved to Brand HQ",
    nicheSavedText: (pillars: boolean): string => (pillars ? "Your positioning, persona and pillars now follow it." : "Your positioning and persona now follow it."),
    replaceConfirm: {
      title: "Replace your pillars?",
      description: (n: number) => `Your active pillars are switched off (never deleted) and this niche's ${n} pillars become your mix. Content keeps its current pillar.`,
      confirm: "Replace pillars",
    },
  },
  done: {
    complete: "Setup complete",
    title: "Your workspace is already set up",
    text: "Detailed setup goes through every step again and updates your Brand HQ — niche, positioning, voice, pillars, goals, primary persona, platforms and posting schedule. Rows are matched by name and updated, never duplicated. Your content and analytics stay as they are.",
    stats: { pillars: "Pillars", personas: "Personas", ideas: "Ideas" },
    resume: "Resume setup",
    startOver: "Start over from my Brand HQ",
    rerun: "Detailed setup",
    rerunNiche: "Re-run Niche Discovery",
    rerunNicheText: "Only find or sharpen your niche — nothing else changes unless you choose to replace your pillars.",
    back: "Back to the app",
  },
  errors: {
    name: "Add your name.",
    role: "Add your role — e.g. Freelance bookkeeper, Founder, Coach.",
    industry: "Add your industry.",
    years: (max: number) => `Use a number between 0 and ${max}.`,
    interests: "Pick at least 2 things you love talking about.",
    skills: "Add at least one skill — or what people ask you for help with.",
    audiences: "Who do you want to help? Pick or type at least one.",
    problems: "Add at least one problem they're struggling with.",
    aims: "Pick at least one thing your brand should do for you.",
    niche: "Choose a niche above or write your own.",
    audience: "Who do you help?",
    result: "What result do you help them get?",
    pillarsMin: (n: number) => `Choose at least ${n} pillars — a mix needs contrast.`,
    pillarsMax: (n: number) => `Choose at most ${n} pillars.`,
    pillarNames: "Every pillar needs a name.",
    pillarsUnique: "Pillar names must be unique.",
    pillarsWhole: "Give every pillar a whole-number target of at least 1%.",
    pillarsTotal: (n: number) => `Targets add up to ${n}% — they need to total 100%.`,
    platforms: "Choose at least one platform.",
    scheduleDay: "Turn on at least one posting day.",
    schedulePlatform: "Every posting day needs a platform.",
    tones: "Pick at least one tone.",
    personality: "Pick at least one personality trait.",
    goalTarget: "Use a target of at least 1, or leave it empty.",
    pickNiche: "Pick a direction, or write your own.",
    ownNiche: "Write your niche in one sentence.",
  },
  goals: {
    awareness: "Awareness",
    authority: "Authority",
    community: "Community",
    leads: "Leads",
    business: "Business",
  },
  periods: { weekly: "Weekly", monthly: "Monthly", quarterly: "Quarterly" },
  days: {
    short: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    long: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
  },
}

export type Copy = typeof EN
