/**
 * Onboarding copy — Taglish, the way Metro Manila creators and professionals actually talk and post.
 * Written, not translated: English for technical terms, Tagalog for the conversation around them.
 */
import type { Copy } from "./copy-en"

export const TL: Copy = {
  lang: { english: "English", taglish: "Taglish", label: "Language" },
  common: {
    continue: "Tuloy",
    back: "Balik",
    toContinue: "para tumuloy",
    stepOf: (n, total) => `Step ${n} of ${total}`,
    setup: "Setup",
    nicheSetup: "Niche Discovery",
    exitSetup: "Lumabas sa setup",
    optional: "Optional",
    edit: "I-edit",
    cancel: "Cancel",
    add: "Idagdag",
    progress: "Progress ng setup",
    stepAria: (n, label, state) => `Step ${n}: ${label}${state === "done" ? ", tapos na" : state === "current" ? ", ngayon" : ""}`,
    srStep: (n, total, title) => `Step ${n} of ${total}: ${title}`,
    upTo: (n) => `Hanggang ${n}.`,
    picked: (n) => `${n} ang napili`,
    remove: (name) => `Tanggalin ang ${name}`,
  },
  phases: { discovery: "Niche Discovery", setup: "I-setup ang Orbi" },
  steps: {
    welcome: {
      short: "Simula",
      title: "Hanapin muna natin ang niche mo",
      description: "Bago tayo gumawa ng content, aalamin muna natin kung ano ang dapat mong makilala — base sa hilig mo, sa galing mo, at sa gusto mong tulungan.",
    },
    hilig: {
      short: "Hilig",
      title: "Anong topic ang kaya mong pag-usapan nang ilang oras?",
      description: "Ang hilig mo — mga bagay na susundan at pag-uusapan mo kahit walang bayad. Pumili ng kahit dalawa.",
    },
    galing: {
      short: "Galing",
      title: "Saan ka magaling?",
      description: "Mga skills na pinagkakatiwalaan na sa'yo ng ibang tao — at ang proof. Mas okay ang specific kaysa impressive.",
    },
    kanino: {
      short: "Kanino",
      title: "Sino ang gusto mong tulungan?",
      description: "Ang mga taong para talaga sa kanila ang content mo: nasaan sila ngayon at ano ang pinoproblema nila.",
    },
    para_saan: {
      short: "Para saan",
      title: "Para saan ang brand mo?",
      description: "Clients, mas magandang career, audience, products… Dito manggagaling ang goals mo at kung paano kikita ang niche mo.",
    },
    niche: {
      short: "Niche",
      title: "Piliin ang niche mo",
      description: "Tatlong direksyon mula sa mga sagot mo. Ikumpara, pumili ng isa at gawin mong sa'yo — o isulat ang sarili mong niche.",
    },
    identity: {
      short: "Ikaw",
      title: "Konting basics tungkol sa'yo",
      description: "Pangalan at role mo — dito manggagaling ang boses ng bawat idea, hook at script.",
    },
    platforms: {
      short: "Platforms",
      title: "Saan ka magpo-post?",
      description: "Mga platform mo, gaano kadalas ka magpo-post at ang weekly schedule mo. Mas panalo ang consistent sa ilang platform kaysa paminsan-minsan sa lahat.",
    },
    voice: {
      short: "Boses",
      title: "Paano ka magsalita?",
      description: "Language, tone at style. Susundan 'to ng Content Strategist at ng bawat AI draft.",
    },
    pillars: {
      short: "Pillars",
      title: "I-confirm ang content pillars mo",
      description: "Ang mga tema na paiikutin mo, galing sa niche mo. I-edit kahit ano — dapat 100% ang total ng targets.",
    },
    strategy: {
      short: "Strategy",
      title: "Ang initial strategy mo",
      description: "Positioning, pillar mix at starter ideas na pasok sa niche mo. Piliin ang ideas mo, tapos i-finish ang setup.",
    },
  },
  welcome: {
    chooseLanguage: "Pumili ng language",
    languageHint: "Pwede kang magpalit anytime sa taas — sa language na pinili mo babalik ang mga suggestion.",
    englishHint: "Malinaw at simpleng English",
    taglishHint: "English at Tagalog, gaya ng normal mong pananalita",
    how: "Paano 'to gumagana",
    flow: [
      { title: "Hanapin ang niche mo", text: "Ang hilig mo, galing mo at ang gusto mong tulungan — magiging tatlong niche direction na pwede mong ikumpara." },
      { title: "I-setup ang Orbi", text: "Platforms, boses at pillars — naka-prefill na base sa niche na pipiliin mo." },
      { title: "Kunin ang unang ideas mo", text: "Starting strategy na may 30 ideas na swak sa niche mo." },
    ],
    time: "Mga 10 minuto · naka-save habang sumasagot ka",
    start: "Simulan na",
  },
  hilig: {
    label: "Ang hilig mo",
    description: "Pumili sa suggestions o i-type ang sarili mo, tapos pindutin ang Enter.",
    placeholder: "hal. K-drama, Running, Kape",
    suggestions: "Suggestions",
    groups: { money: "Pera at negosyo", work: "Trabaho at career", digital: "Digital at tech", life: "Buhay at wellness", hobbies: "Hobbies at creative" },
    count: (n) => (n < 2 ? `${n} sa 2 minimum` : `${n} ang napili`),
    test: "Quick test: ipo-post mo pa rin ba 'to kahit 50 posts na ang walang likes? Hilig mo 'yan.",
  },
  galing: {
    skills: "Ang skills mo",
    skillsDescription: "Pumili o i-type kung saan ka magaling. Hanggang 10.",
    skillsPlaceholder: "hal. Bookkeeping, Video editing, Pagtuturo",
    groups: { business: "Business at operations", marketing: "Marketing at content", tech: "Tech at tools", people: "Pagtuturo at hands-on" },
    help: "Saan ka madalas hingan ng tulong?",
    helpPlaceholder: "hal. Paano mag-price ng cakes, paano mag-file ng taxes as freelancer",
    years: "Ilang taon ka na dito?",
    yearsSuffix: "taon",
    proof: "Results o proof",
    proofDescription: "Numbers, clients, before-and-after — kahit ano na nagpapakitang gumagana ang ginagawa mo.",
    proofPlaceholder: "hal. Natulungan ko ang 40+ freelancers mag-register sa BIR",
    story: "Maikling proof story",
    storyDescription: "Optional — mase-save sa Story Vault mo at gagamitin sa mga unang ideas mo.",
    storyPlaceholder: "hal. ₱500 lang ang binayad ng una kong client para sa logo. After two years, may team na ako ng tatlo…",
  },
  kanino: {
    who: "Sino ang gusto mong tulungan?",
    whoDescription: "Pumili o mag-type ng isa o higit pa. Ang una ang magiging primary persona mo.",
    whoPlaceholder: "hal. Home bakers, Bagong nurses, Online sellers",
    stage: "Nasaan sila ngayon?",
    stagePlaceholder: "hal. First year pa lang sa freelancing, walang idea sa taxes",
    level: "Level nila",
    levels: { Beginner: "Nagsisimula pa lang", Intermediate: "May experience na", Advanced: "Advanced na", Mixed: "Halo-halo" },
    goal: "Saan nila gustong makarating?",
    goalPlaceholder: "hal. Kumita sa baking nang hindi nagtatrabaho nang libre",
    problems: "Mga problema nila",
    problemsDescription: "Sa sarili nilang salita, simula sa pinakamasakit. Mas matalas ang niche kapag tatlo o higit pa.",
    problemsPlaceholder: "hal. Hindi alam paano mag-file ng taxes",
    addProblem: "Idagdag",
    problemsHint: (n) => (n >= 3 ? "Ayos — sapat na 'yan para makabuo ng niche." : `Magdagdag pa ng ${3 - n} para mas tumalas ang niche.`),
    platforms: "Saan sila madalas tumambay online",
    platformsDescription: "Ito ang isa-suggest naming platforms mo mamaya.",
  },
  paraSaan: {
    aims: "Pumili ng hanggang 3",
    aimsDescription: "Saan dapat humantong ang lahat ng content na 'to?",
    options: {
      clients: { title: "Magka-clients", text: "Freelance, consulting o services" },
      career: { title: "Mag-grow sa career", text: "Mas magandang trabaho, promotion o career shift" },
      audience: { title: "Magkaroon ng audience", text: "Reach at influence" },
      products: { title: "Magbenta ng products", text: "Templates, courses, merch" },
      speaking: { title: "Speaking at collabs", text: "Talks, media, partnerships" },
      community: { title: "Bumuo ng community", text: "Mga taong sabay-sabay natututo" },
    },
    primary: "Main goal",
    primaryDescription: "Dito manggagaling ang goals mo sa app. Piliin kung alin ang mauuna.",
    targets: "Targets",
    targetsDescription: "Ano ang itsura ng success. Pwede mo 'tong baguhin anytime sa Strategy → Goals.",
    primaryTag: "Primary",
    secondaryTag: "Secondary",
    noTarget: "Walang target",
    targetAria: (goal, metric) => `${goal} target (${metric})`,
    periodAria: (goal) => `${goal} period`,
  },
  niche: {
    generating: "Hinahanap ang tatlong niche direction mula sa mga sagot mo…",
    offlineNote: "Binuo mula sa mga sagot mo gamit ang offline templates — pwedeng i-edit lahat.",
    aiNote: "Dinraft mula sa mga sagot mo — pwedeng i-edit lahat.",
    regenerate: "Gumawa ulit",
    regenerating: "Gumagawa ulit…",
    errorTitle: "Hindi nakahanap ng niche directions",
    errorHint: "Subukan ulit, o isulat ang sarili mong niche sa baba — naka-save ang mga sagot mo.",
    tryAgain: "Subukan ulit",
    notesTitle: "Para mas tumalas",
    kinds: { expertise: "Galing-first", passion: "Hilig-first", audience: "Audience-first" },
    kindHints: { expertise: "Nakabase sa galing mo", passion: "Nakabase sa hilig mo", audience: "Nakabase sa gusto mong tulungan" },
    fit: { passion: "Hilig", expertise: "Galing", demand: "Demand" },
    fitAria: (label, score) => `${label} ${score} sa 10`,
    audience: "Audience",
    pillars: "Pillars",
    posts: "Sample posts",
    money: "Paano kikita",
    why: "Bakit swak",
    risk: "Ingat",
    more: "Posts at monetization",
    less: "Itago",
    choose: "Piliin 'to",
    chosen: "Napili",
    ownTitle: "Isulat ang sarili mo",
    ownText: "May niche ka na bang naiisip? Isulat mo sa isang sentence.",
    ownButton: "Isusulat ko",
    yours: "Ang niche mo",
    yoursDescription: "Isang sentence. I-edit hanggang tunog ikaw na.",
    nicheLabel: "Niche statement",
    nichePlaceholder: "hal. Taxes at bookkeeping na pinasimple para sa mga bagong Pinoy freelancers",
    positioning: "Ang positioning mo",
    positioningDescription: "Isang sentence na kayang ulitin ng audience mo tungkol sa'yo.",
    positioningEmpty: "Lalabas dito ang positioning statement mo habang nagta-type ka.",
    leads: { audience: "I help", result: "to", method: "through" },
    hints: { audience: "sino ang tinutulungan mo", result: "anong resulta ang maibibigay mo", method: "paano mo ito ginagawa" },
    placeholders: { audience: "hal. new freelancers", result: "hal. mag-file ng taxes nang walang kaba", method: "hal. simple na bookkeeping systems" },
    appliedFirst: "Sumusunod na sa niche na 'to ang pillars, positioning at industry mo.",
    appliedRerun: "Sumusunod na sa niche na 'to ang positioning mo. Hindi gagalawin ang pillars mo hangga't hindi mo pinapalitan.",
    replacePillars: (n) => `Palitan na rin ang pillars ko ng ${n} pillars ng niche na 'to`,
    replacePillarsHint: "Io-off lang ang current pillars, hindi buburahin.",
    pickFirst: "Pumili ng direction sa taas o isulat ang sarili mong niche.",
    outOfTen: (n) => `${n}/10`,
  },
  clarity: {
    title: "Clarity check",
    description: "Mabilis na check bago tumuloy — payo lang, hindi harang.",
    waiting: "Tatakbo 'to kapag pumili o nagsulat ka na ng niche.",
    allGood: "Malinaw at specific — ready na para i-setup ang Orbi.",
    toSharpen: (n) => `${n} pang dapat patalasin`,
    fix: "Ayusin",
    items: {
      sentence: { ok: "Isang malinaw na sentence", warn: "Gawing isang malinaw na sentence na 4–28 words — hindi listahan." },
      audience: { ok: "Specific na audience", warn: "Pangalanan ang specific na audience. Kapag “lahat”, walang tatamaan." },
      problems: {
        ok: "Sapat na totoong problema ng audience",
        warn: (n) => `Magdagdag pa ng ${3 - n} totoong problema ng audience — ito ang sinasagot ng content mo.`,
      },
      range: { ok: "Sapat na topics para sa 30 ideas", warn: "Magdagdag ng topics o pillars para hindi paulit-ulit ang 30 ideas — at least 4 pillars." },
      money: { ok: "May monetization path", warn: "Piliin kung para saan ang brand mo para may patutunguhan ang niche." },
    },
  },
  identity: {
    niche: "Ang niche mo",
    changeNiche: "Palitan",
    name: "Pangalan mo",
    namePlaceholder: "hal. Maria Santos",
    brandName: "Brand name",
    brandNamePlaceholder: "hal. Santos Studio",
    brandNameHint: "Iwanang blangko kung ikaw mismo ang brand.",
    role: "Role",
    rolePlaceholder: "hal. Freelance bookkeeper",
    industry: "Industry",
    industryPlaceholder: "hal. Accounting, Food, Education",
    industryHint: "Naka-prefill mula sa niche mo.",
    location: "Location",
    locationPlaceholder: "hal. Manila, Philippines",
  },
  platforms: {
    audienceUses: "Dito madalas ang audience mo",
    useThese: "Gamitin 'to",
    group: "Main platforms",
    note: "Magkakaroon ng active na platform strategy ang mga pinili mo; naka-off muna ang iba hangga't hindi mo binubuksan sa Strategy → Platforms.",
    hints: {
      facebook: "Groups, mahahabang post at community — nandito na ang karamihan ng Pinoy",
      tiktok: "Short videos na may pinakamalaking reach para sa bagong creators",
      instagram: "Carousels, Reels at visual na portfolio",
      youtube: "Mahahabang video na nase-search, at Shorts",
      linkedin: "Professionals, B2B at career content",
      x: "Mabilis na takes, threads at usapang industry",
      threads: "Casual na text posts at kwentuhan",
    },
  },
  posting: {
    weekly: "Weekly post target",
    weeklyDescription: "Isang post sa isang platform = isa. Baguhin ang total o ang hati — sabay silang mag-a-adjust.",
    perWeekLabel: "Posts kada linggo",
    perWeekSuffix: "/ linggo",
    perPlatformAria: (platform) => `${platform} posts kada linggo`,
    tooMany: "Dalawa o higit pang post 'yan kada araw. Magsimula nang mas mababa at taasan kapag kaya na ng content buffer mo.",
    schedule: "Posting schedule",
    scheduleDescription: "Recurring na weekly slots — ginagamit ng calendar at ng What-to-post.",
    postsPerWeek: (n) => `${n} posts / linggo`,
    typeAria: "Uri ng schedule",
    modes: {
      recommended: { title: "Recommended na weekly strategy", text: "May tema kada araw para sa bawat uri ng pillar, naka-adjust sa platforms mo." },
      custom: { title: "Custom kada araw", text: "Ikaw ang pipili ng araw, tema, platform at oras." },
    },
    recommendedAria: "Recommended na weekly schedule",
    customAria: "Custom na weekly schedule",
    noPost: "Walang post",
    themePlaceholder: "Tema, hal. Tutorial",
    postOn: (day) => `Mag-post sa ${day}`,
    themeAria: (day) => `Tema sa ${day}`,
    platformsAria: (day) => `Platforms sa ${day}`,
    timeAria: (day) => `Oras sa ${day}`,
  },
  voice: {
    language: "Language",
    languageNotes: {
      english: "Malinaw at conversational na English.",
      tagalog: "Natural na Filipino — parang nag-e-explain ka sa kaibigan.",
      taglish: "English at Tagalog na halo, gaya ng totoo mong pananalita.",
    },
    tone: "Tone",
    toneDescription: (n) => `Pumili ng hanggang ${n}. Kapag pumili ka ng bago, papalitan ang pinakaluma.`,
    personality: "Personality",
    personalityDescription: (n) => `Hanggang ${n} traits na dapat maramdaman ng mga tao sa content mo.`,
    cta: "Call-to-action style",
    ctaDescription: "Paano ka karaniwang nag-a-ask ng action sa dulo ng post.",
    ctaPresetsAria: "CTA style presets",
    ctaPresets: [
      { label: "Soft", text: "Soft by default — mag-comment ng keyword para makuha ang resource, o i-DM ako ng sitwasyon mo." },
      { label: "Kwentuhan", text: "Magtapos sa tanong na kayang sagutin ng mga tao mula sa sarili nilang experience." },
      { label: "Direct", text: "Direct lang sa conversion posts — mag-book ng call o kunin ang offer sa link." },
    ],
    ctaPlaceholder: "O isulat ang sarili mo — hal. I-comment ang GUIDE at ise-send ko sa'yo ang template.",
    rules: "Brand rules",
    rulesDescription: "Optional na guardrails na susundan ng bawat draft.",
    always: "Palagi",
    never: "Hindi kailanman",
    alwaysPlaceholder: "hal. Gumamit ng totoong numbers. Aminin kapag nagkamali ako.",
    neverPlaceholder: "hal. Mag-promise ng overnight results. Pangalanan ang clients.",
  },
  pillars: {
    total: (n) => `Total ${n}%`,
    count: (n) => `${n} pillars`,
    left: (n) => `${n}% pa ang kulang`,
    over: (n) => `${n}% ang sobra`,
    rebalance: "I-rebalance sa 100%",
    even: "Hatiin nang pantay",
    listAria: "Content pillars",
    noDescription: "Walang description",
    nicheBadge: "Niche",
    customBadge: "Custom",
    targetAria: (name) => `Target percentage ng ${name}`,
    fromNiche: "Pillars para sa niche mo",
    fromNicheText: "Ito ang mga pillar na swak sa niche na pinili mo.",
    useNiche: "Gamitin ang pillars na 'to",
    general: "General pillars na pwedeng idagdag",
    addCustom: "Magdagdag ng custom pillar",
    name: "Pangalan ng pillar",
    namePlaceholder: "hal. Freelancer Q&A",
    description: "Description",
    descriptionPlaceholder: "hal. Sumasagot sa isang totoong tanong kada linggo",
    addPillar: "Idagdag ang pillar",
    nameMissing: "Pangalanan ang pillar.",
    nameTaken: "May pillar ka nang ganyan ang pangalan.",
    tooMany: (n) => `Hanggang ${n} pillars lang ang pwede.`,
    applied: "Nagamit na ang niche pillars",
  },
  strategy: {
    drafting: "Dinadraft ang positioning, pillar mix at hanggang 30 starter ideas na pasok sa niche mo…",
    errorTitle: "Hindi na-generate ang strategy mo",
    errorHint: "Subukan ulit, o i-finish na ang setup at mag-generate ng ideas mamaya sa Idea Generator — naka-save ang mga sagot mo either way.",
    tryAgain: "Subukan ulit",
    offlineNote: "Binuo mula sa mga sagot mo gamit ang offline templates — pwedeng i-edit lahat.",
    aiNote: "Dinraft mula sa mga sagot mo — i-edit kahit ano bago mag-finish.",
    regenerate: "Gumawa ulit",
    regenerating: "Gumagawa ulit…",
    outOfDate: "Luma na",
    outOfDateText: "— may nagbago sa mga sagot mo mula nang ma-draft 'to. Gumawa ulit para ma-refresh ang ideas.",
    previousDraft: "Nandito pa rin ang dati mong draft.",
    niche: "Niche",
    positioning: "Positioning statement",
    positioningEmpty: "Idagdag sa Niche step kung sino ang tinutulungan mo at anong resulta ang binibigay mo.",
    suggested: "Suggestion",
    useThis: "Gamitin 'to",
    editToUse: "I-edit ang Niche step kung gusto mong gamitin ang wording na 'to.",
    knownFor: "Known for",
    pov: "Point of view",
    povDescription: "Mga paniniwalang paulit-ulit mong babalikan.",
    povPlaceholder: "Ano ang pinaniniwalaan mo na hindi pinaniniwalaan ng iba sa space mo?",
    pillars: "Content pillars",
    pillarsDescription: (n, total) => `${n} pillars · ${total}% total`,
    suggestedMix: "Suggested mix — naka-weight sa goals mo",
    useSuggestedMix: "Gamitin ang suggested mix",
    ideas: "Mga unang content ideas",
    ideasCount: (selected, total) => `${selected} sa ${total} ang napili · mase-save sa Idea Bank · i-click ang title para i-edit`,
    selectAll: "Piliin lahat",
    clear: "Alisin lahat",
    keepIdea: (title) => `Isama ang “${title}”`,
    ideaTitle: "Title ng idea",
    ideaPillar: (title) => `Pillar ng “${title}”`,
    noPillar: "Walang pillar",
    noIdeas: "Walang ideas sa draft na 'to",
    noIdeasText: "Gumawa ulit para makakuha ng starter ideas na nakabase sa niche mo at sa mga problema ng audience mo.",
    willAdd: (n) => `${n} ideas ang madadagdag`,
    toasts: { positioning: "Na-update ang positioning", knownFor: "Na-update ang known-for", pov: "Na-update ang point of view", mix: "Nagamit ang suggested pillar mix", undo: "I-undo" },
    regenerateConfirm: {
      title: "Gumawa ulit ng strategy?",
      changed: "May nagbago sa mga sagot mo. Papalitan ng bagong strategy ang current ideas, pati ang mga in-edit mong title, selection at pillar picks.",
      manual: "Makakakuha ka ng bagong set ng ideas. Mapapalitan ang mga in-edit mong title, selection at pillar picks.",
      confirm: "Gumawa ulit",
    },
  },
  summary: {
    title: "Ano ang gagawin ng Finish setup",
    description: "Mase-save lahat sa workspace mo at pwede pa ring i-edit.",
    niche: "Niche",
    brandHq: "Brand HQ",
    brandHqDetail: (who) => `${who || "Ang profile mo"} — positioning, boses at brand rules`,
    goal: "Goal",
    goals: "Goals",
    chooseGoal: "Pumili ng primary goal",
    primary: "Primary",
    secondary: "Secondary",
    pillars: "Content pillars",
    persona: "Primary persona",
    personaDetail: (name, n) => `${name || "Walang pangalan"} · ${n} problema para sa Problem Bank mo`,
    platforms: "Platforms",
    postsPerWeek: (n) => `${n} posts / linggo`,
    schedule: "Posting schedule",
    scheduleDetail: (n, custom) => `${n} weekly slots · ${custom ? "custom" : "recommended strategy"}`,
    ideaBank: "Idea Bank",
    ideaDetail: (n) => `${n} starter ideas`,
    storyVault: "Story Vault",
    storyDetail: "Ang proof story mo",
    editAria: (title) => `I-edit ang ${title}`,
  },
  finish: {
    finish: "I-finish ang setup",
    generate: "I-generate ang strategy ko",
    regenerate: "I-regenerate ang strategy",
    review: "Tingnan ang strategy",
    showNiches: "Ipakita ang niche options ko",
    saveNiche: "I-save ang niche ko",
    settingUp: "Sine-setup ang workspace mo…",
    savingNiche: "Sine-save ang niche mo…",
    welcome: (name) => `Welcome${name ? `, ${name}` : ""} — ready na ang workspace mo`,
    summary: (pillars, ideas, weekly) => `Ready na ang ${pillars} pillars${ideas ? `, ${ideas} ideas sa Idea Bank mo` : ""} at ang ${weekly}-post na weekly plan.`,
    failed: "Hindi natapos ang setup",
    attention: "May ilang sagot na kailangang ayusin",
    nicheSaved: "Naka-save na sa Brand HQ ang niche mo",
    nicheSavedText: (pillars) => (pillars ? "Sumusunod na rito ang positioning, persona at pillars mo." : "Sumusunod na rito ang positioning at persona mo."),
    replaceConfirm: {
      title: "Palitan ang pillars mo?",
      description: (n) => `Io-off ang active pillars mo (hindi buburahin) at ang ${n} pillars ng niche na 'to ang magiging mix mo. Mananatili sa dating pillar ang content mo.`,
      confirm: "Palitan ang pillars",
    },
  },
  done: {
    complete: "Tapos na ang setup",
    title: "Naka-setup na ang workspace mo",
    text: "Kapag inulit ang setup, maa-update ang Brand HQ mo — niche, positioning, boses, pillars, goals, primary persona, platforms at posting schedule. Mina-match ang rows by name at ina-update, hindi dinodoble. Hindi gagalawin ang content at analytics mo.",
    stats: { pillars: "Pillars", personas: "Personas", ideas: "Ideas" },
    resume: "Ituloy ang setup",
    startOver: "Magsimula ulit mula sa Brand HQ ko",
    rerun: "Ulitin ang setup",
    rerunNiche: "Ulitin ang Niche Discovery",
    rerunNicheText: "Hanapin o patalasin lang ang niche mo — walang ibang magbabago maliban kung papalitan mo ang pillars.",
    back: "Bumalik sa app",
  },
  errors: {
    name: "Ilagay ang pangalan mo.",
    role: "Ilagay ang role mo — hal. Freelance bookkeeper, Founder, Coach.",
    industry: "Ilagay ang industry mo.",
    years: (max) => `Numero mula 0 hanggang ${max}.`,
    interests: "Pumili ng kahit 2 bagay na gustong-gusto mong pag-usapan.",
    skills: "Magdagdag ng kahit isang skill — o kung saan ka madalas hingan ng tulong.",
    audiences: "Sino ang gusto mong tulungan? Pumili o mag-type ng kahit isa.",
    problems: "Magdagdag ng kahit isang problema nila.",
    aims: "Pumili ng kahit isang bagay na dapat gawin ng brand mo para sa'yo.",
    niche: "Pumili ng niche sa taas o isulat ang sarili mo.",
    audience: "Sino ang tinutulungan mo?",
    result: "Anong resulta ang maibibigay mo sa kanila?",
    pillarsMin: (n) => `Pumili ng kahit ${n} pillars — kailangan ng contrast ang mix.`,
    pillarsMax: (n) => `Hanggang ${n} pillars lang.`,
    pillarNames: "Kailangan ng pangalan ang bawat pillar.",
    pillarsUnique: "Dapat magkakaiba ang pangalan ng pillars.",
    pillarsWhole: "Bigyan ang bawat pillar ng buong numero na target, at least 1%.",
    pillarsTotal: (n) => `${n}% ang total ng targets — dapat eksaktong 100%.`,
    platforms: "Pumili ng kahit isang platform.",
    scheduleDay: "Mag-on ng kahit isang posting day.",
    schedulePlatform: "Kailangan ng platform ang bawat posting day.",
    tones: "Pumili ng kahit isang tone.",
    personality: "Pumili ng kahit isang personality trait.",
    goalTarget: "Target na at least 1, o iwanang blangko.",
  },
  goals: {
    awareness: "Awareness",
    authority: "Authority",
    community: "Community",
    leads: "Leads",
    business: "Business",
  },
  periods: { weekly: "Kada linggo", monthly: "Kada buwan", quarterly: "Kada quarter" },
  days: {
    short: ["Lin", "Lun", "Mar", "Miy", "Huw", "Biy", "Sab"],
    long: ["Linggo", "Lunes", "Martes", "Miyerkules", "Huwebes", "Biyernes", "Sabado"],
  },
}
