/**
 * Niche knowledge for the offline Niche Discovery engine: topic areas Filipino creators and professionals
 * build brands around, each with bilingual (English / Taglish) copy — a default audience, the result that
 * audience wants, a method, niche-specific pillars, monetization paths, why there's demand and, where the
 * topic is sensitive, an honest risk. The engine always leads with the creator's own words; a domain only
 * adds what a good strategist would know about the space.
 */

/** [English, Taglish] */
export type Bi = readonly [string, string]

export interface NicheDomain {
  id: string
  /** Tested against lower-cased interests, skills, audiences and problems. */
  match: RegExp
  /** Short topic, used mid-sentence ("personal finance"). */
  topic: Bi
  /** A short noun for "___ for [audience]" names ("money", "food business"). */
  theme: Bi
  /** Identity prefill (Brand HQ industry). */
  industry: string
  /** Typical audience when the creator hasn't named one. */
  audience: Bi
  /** What that audience wants — a verb phrase ("save and invest consistently…"). */
  result: Bi
  /** How the creator delivers it ("simple money systems…"). */
  method: Bi
  /** [name, description] — named for the niche, never generic Education/Authority. */
  pillars: readonly (readonly [Bi, Bi])[]
  monetization: readonly Bi[]
  /** Why people already look for this. */
  demand: Bi
  /** 1–10, how actively people seek this content. */
  demandScore: number
  /** An honest caution for sensitive topics (money, health, legal…). */
  risk?: Bi
}

export const NICHE_DOMAINS: readonly NicheDomain[] = [
  {
    id: "taxes",
    match: /\b(tax(es)?|bir|bookkeep\w*|accounting|accountants?|cpa|payroll|invoic\w*|audit\w*|financial statements?)\b/,
    topic: ["taxes and bookkeeping", "taxes at bookkeeping"],
    theme: ["taxes", "taxes"],
    industry: "Accounting & taxes",
    audience: ["freelancers and small business owners", "freelancers at small business owners"],
    result: ["stay tax-compliant and know their real numbers", "maging tax-compliant at alam ang totoong numbers nila"],
    method: ["plain-language guides and simple bookkeeping systems", "simple na guides at bookkeeping systems"],
    pillars: [
      [["BIR made simple", "BIR made simple"], ["Registration, filing and deadlines, step by step", "Registration, filing at deadlines — step by step"]],
      [["Bookkeeping systems", "Bookkeeping systems"], ["Simple ways to track income and expenses every week", "Simple na paraan para i-track ang income at expenses every week"]],
      [["Tax season survival", "Tax season survival"], ["Checklists and reminders before every deadline", "Checklists at reminders bago ang bawat deadline"]],
      [["Know your numbers", "Know your numbers"], ["Profit, cash flow and pricing — what the numbers really say", "Profit, cash flow at pricing — ano talaga ang sinasabi ng numbers"]],
      [["Client cases", "Client cases"], ["Anonymised cases: the mess, the fix, the result", "Anonymous na cases: ang gulo, ang fix, ang resulta"]],
    ],
    monetization: [
      ["BIR registration and filing service", "BIR registration at filing service"],
      ["Monthly bookkeeping retainer", "Monthly bookkeeping retainer"],
      ["Bookkeeping and tax templates", "Bookkeeping at tax templates"],
      ["Tax-season workshops", "Tax-season workshops"],
    ],
    demand: [
      "Every deadline brings the same anxious questions, and very few people explain BIR in plain language.",
      "Every deadline, pare-pareho ang kinakabahang tanong ng mga tao — at kaunti lang ang nag-e-explain ng BIR sa simpleng paraan.",
    ],
    demandScore: 8,
    risk: [
      "Rules change — date your posts and point people to official BIR sources for anything formal.",
      "Nagbabago ang rules — lagyan ng date ang posts mo at i-refer ang mga tao sa official BIR sources.",
    ],
  },
  {
    id: "finance",
    match: /\b(personal finance|finance|money|budget\w*|ipon|savings?|saving|invest\w*|stocks?|mp2|insurance|debt|utang|emergency fund|financial\w*|pera)\b/,
    topic: ["personal finance", "personal finance"],
    theme: ["money", "pera"],
    industry: "Personal finance",
    audience: ["young professionals", "young professionals"],
    result: ["save and invest consistently, even without a big income", "makaipon at mag-invest nang consistent, kahit hindi malaki ang kita"],
    method: ["simple money systems they can run every payday", "simple na money systems na kaya gawin every sahod"],
    pillars: [
      [["Budget & ipon systems", "Budget & ipon systems"], ["Payday routines, budgeting methods and ipon challenges that stick", "Payday routine, budgeting at ipon challenges na talagang tumatagal"]],
      [["Investing basics", "Investing basics"], ["MP2, index funds and insurance — explained without jargon", "MP2, index funds at insurance — explained nang walang jargon"]],
      [["Money mistakes", "Money mistakes"], ["Common money mistakes and how to undo them", "Mga common na money mistakes at paano ito ayusin"]],
      [["Real money stories", "Real money stories"], ["Honest numbers from real budgets and journeys", "Totoong numbers mula sa totoong budget at journey"]],
      [["Money mindset", "Money mindset"], ["Beliefs about money that keep people broke — and better ones", "Mga paniniwala sa pera na nagpapahirap — at mas maayos na mindset"]],
    ],
    monetization: [
      ["Budget and ipon templates", "Budget at ipon templates"],
      ["1:1 money coaching sessions", "1:1 money coaching sessions"],
      ["Money workshops for companies and schools", "Money workshops para sa companies at schools"],
      ["Disclosed affiliate partnerships with banks and apps", "Affiliate partnerships sa banks at apps (with disclosure)"],
    ],
    demand: [
      "Money is searched every payday — “paano mag-ipon” never goes out of season.",
      "Every sahod, sine-search 'to — hindi nawawala sa uso ang “paano mag-ipon”.",
    ],
    demandScore: 9,
    risk: [
      "Money advice carries weight — share what you did and why, never guarantees or get-rich promises.",
      "Mabigat ang money advice — i-share kung ano ang ginawa mo at bakit, hindi guarantees o “yayaman ka agad” na promise.",
    ],
  },
  {
    id: "freelancing",
    match: /\b(freelanc\w*|virtual assist\w*|va|vas|remote work\w*|work from home|wfh|upwork|onlinejobs|online jobs?|home-?based|side hustles?|sidelines?|raket)\b/,
    topic: ["freelancing", "freelancing"],
    theme: ["clients", "clients"],
    industry: "Freelancing & remote work",
    audience: ["aspiring freelancers", "aspiring freelancers"],
    result: ["land their first clients and earn from home", "makakuha ng unang clients at kumita from home"],
    method: ["step-by-step client-getting systems", "step-by-step na sistema sa pagkuha ng clients"],
    pillars: [
      [["Getting clients", "Getting clients"], ["Profiles, proposals and outreach that actually get replies", "Profile, proposal at outreach na talagang nirereplyan"]],
      [["Skills that pay", "Skills that pay"], ["The skills clients hire for and how to learn them fast", "Mga skills na hina-hire ng clients at paano ito matutunan agad"]],
      [["Freelance money", "Freelance money"], ["Rates, payments and saving on irregular income", "Rates, payments at pag-iipon kahit irregular ang income"]],
      [["Work-from-home life", "Work-from-home life"], ["Routines, boundaries and the real side of working from home", "Routine, boundaries at ang totoong buhay ng WFH"]],
      [["Freelancer wins & fails", "Freelancer wins & fails"], ["Real stories from client work — the good and the messy", "Totoong kwento mula sa client work — ang maganda at ang magulo"]],
    ],
    monetization: [
      ["Freelancing course or cohort", "Freelancing course o cohort"],
      ["1:1 profile and proposal reviews", "1:1 profile at proposal reviews"],
      ["Subcontracting overflow client work", "Subcontracting ng overflow na client work"],
      ["Proposal, contract and rate-sheet templates", "Templates: proposal, contract at rate sheet"],
    ],
    demand: [
      "Thousands of Filipinos look for their first online client every month, and scams make trusted guides valuable.",
      "Libo-libong Pinoy ang naghahanap ng unang online client every month — at dahil sa scams, mahalaga ang trusted na guide.",
    ],
    demandScore: 9,
    risk: [
      "It's a crowded space — your edge has to be a specific skill or client type, not freelancing in general.",
      "Siksikan na 'to — ang edge mo dapat specific na skill o type ng client, hindi lang “freelancing” in general.",
    ],
  },
  {
    id: "ecommerce",
    match: /\b(e-?commerce|online sell\w*|online shop\w*|shopee|lazada|tiktok shop|resell\w*|dropship\w*|online business\w*|sellers?)\b/,
    topic: ["online selling", "online selling"],
    theme: ["online selling", "online selling"],
    industry: "E-commerce",
    audience: ["small online sellers", "small online sellers"],
    result: ["turn their online shop into a steady, profitable business", "gawing steady at profitable na negosyo ang online shop nila"],
    method: ["simple selling systems and honest numbers", "simple na selling systems at honest na numbers"],
    pillars: [
      [["Shopee & TikTok Shop playbook", "Shopee & TikTok Shop playbook"], ["Listings, vouchers, live selling and platform changes", "Listings, vouchers, live selling at platform updates"]],
      [["Products & pricing", "Products & pricing"], ["Choosing products and pricing for real profit", "Pagpili ng products at pricing para sa totoong kita"]],
      [["Content that sells", "Content that sells"], ["Videos and lives that actually move stock", "Videos at lives na talagang nakakabenta"]],
      [["Seller numbers", "Seller numbers"], ["Margins, cash flow and inventory without the guesswork", "Margins, cash flow at inventory nang walang hula"]],
      [["Shop stories", "Shop stories"], ["Behind the scenes of real shops — wins, losses, lessons", "Behind the scenes ng totoong shops — panalo, talo, lessons"]],
    ],
    monetization: [
      ["Store audits and seller coaching", "Store audits at seller coaching"],
      ["Pricing and inventory templates", "Pricing at inventory templates"],
      ["Paid seller community", "Paid na seller community"],
      ["Brand partnerships and affiliate commissions", "Brand partnerships at affiliate commissions"],
    ],
    demand: [
      "Online selling keeps growing in the Philippines, and new sellers constantly ask how to make it actually profitable.",
      "Tuloy-tuloy ang paglaki ng online selling sa Pilipinas — at laging tanong ng bagong sellers kung paano 'to gagawing profitable.",
    ],
    demandScore: 8,
  },
  {
    id: "marketing",
    match: /\b(digital marketing|marketing|ads|advertis\w*|facebook ads|meta ads|google ads|social media manag\w*|smm|seo|copywrit\w*|funnels?|lead gen\w*|branding|email marketing)\b/,
    topic: ["digital marketing", "digital marketing"],
    theme: ["marketing", "marketing"],
    industry: "Digital marketing",
    audience: ["small business owners", "small business owners"],
    result: ["get customers from social media without wasting their ad budget", "makakuha ng customers sa social media nang hindi nasasayang ang ad budget"],
    method: ["simple, tested marketing systems", "simple at tested na marketing systems"],
    pillars: [
      [["Ads that convert", "Ads that convert"], ["Targeting, creatives and budgets explained with real numbers", "Targeting, creatives at budget — explained gamit ang totoong numbers"]],
      [["Posts that sell", "Posts that sell"], ["Content that turns followers into customers", "Content na ginagawang customers ang followers"]],
      [["Campaign teardowns", "Campaign teardowns"], ["Breaking down campaigns that worked — and why", "Hinihimay ang mga campaign na gumana — at bakit"]],
      [["Marketing tools", "Marketing tools"], ["Apps and workflows that save hours every week", "Apps at workflows na nakakatipid ng oras every week"]],
      [["Client results", "Client results"], ["Before-and-after stories from real campaigns", "Before-and-after na kwento mula sa totoong campaigns"]],
    ],
    monetization: [
      ["Done-for-you ads or social media management", "Done-for-you na ads o social media management"],
      ["Marketing audits", "Marketing audits"],
      ["Workshops or a course for business owners", "Workshops o course para sa business owners"],
      ["Templates and swipe files", "Templates at swipe files"],
    ],
    demand: [
      "Every small business needs customers online, and most owners want someone who explains — not just another agency.",
      "Kailangan ng bawat small business ng customers online — at karamihan ng owners, gusto ng nag-e-explain, hindi lang agency.",
    ],
    demandScore: 8,
  },
  {
    id: "creator",
    match: /\b(content creat\w*|creators?|youtube|youtubers?|tiktok|vlog\w*|influenc\w*|personal brand\w*|social media|podcast\w*|streaming)\b/,
    topic: ["content creation", "content creation"],
    theme: ["content", "content"],
    industry: "Content creation",
    audience: ["aspiring creators", "aspiring creators"],
    result: ["grow an audience and turn it into income", "mag-grow ng audience at gawing income ito"],
    method: ["repeatable content systems", "repeatable na content systems"],
    pillars: [
      [["Content systems", "Content systems"], ["Planning, batching and posting without burning out", "Planning, batching at posting nang hindi nabu-burnout"]],
      [["Hooks & storytelling", "Hooks & storytelling"], ["What makes people stop scrolling — with examples", "Ano ang nagpapahinto sa pag-scroll — with examples"]],
      [["Growth experiments", "Growth experiments"], ["What I tested this month and what happened", "Ano ang tinest ko this month at ano ang nangyari"]],
      [["Creator money", "Creator money"], ["Brand deals, rates and income streams — the honest version", "Brand deals, rates at income streams — the honest version"]],
      [["Creator life", "Creator life"], ["The real behind-the-scenes of making content", "Ang totoong behind-the-scenes ng paggawa ng content"]],
    ],
    monetization: [
      ["Brand deals and sponsorships", "Brand deals at sponsorships"],
      ["Coaching for new creators", "Coaching para sa bagong creators"],
      ["Editing or content services", "Editing o content services"],
      ["Templates and presets", "Templates at presets"],
    ],
    demand: [
      "Everyone wants to grow online, but few creators share honest numbers and systems.",
      "Lahat gustong mag-grow online, pero kaunti lang ang nagsha-share ng honest na numbers at systems.",
    ],
    demandScore: 7,
    risk: [
      "Content about content can become a loop — show results from your own account first.",
      "Pwedeng maging paikot-ikot ang content about content — ipakita muna ang results ng sarili mong account.",
    ],
  },
  {
    id: "career",
    match: /\b(career\w*|job hunt\w*|resumes?|cv|interview\w*|promotions?|corporate|bpo|call cent\w*|hr|human resources?|recruit\w*|hiring|fresh grads?|jobs?|trabaho|salary|sweldo|linkedin)\b/,
    topic: ["career growth", "career growth"],
    theme: ["career", "career"],
    industry: "Careers & HR",
    audience: ["fresh grads and young professionals", "fresh grads at young professionals"],
    result: ["land better jobs and grow their salary faster", "makakuha ng mas magandang trabaho at mapalaki ang sweldo nila"],
    method: ["insider hiring advice and practical career moves", "insider na hiring advice at practical na career moves"],
    pillars: [
      [["Resumes & interviews", "Resumes & interviews"], ["What recruiters actually look for, with before-and-afters", "Ano talaga ang hinahanap ng recruiters — may before-and-after"]],
      [["Career moves", "Career moves"], ["Promotions, job switches and salary negotiation", "Promotions, paglipat ng trabaho at salary negotiation"]],
      [["Workplace skills", "Workplace skills"], ["Communication, managing up and the skills nobody teaches", "Communication, managing up at mga skills na hindi itinuturo"]],
      [["Corporate real talk", "Corporate real talk"], ["Honest takes on office life, bosses and burnout", "Honest na takes sa office life, bosses at burnout"]],
      [["Career journeys", "Career journeys"], ["From first job to where people are now", "Mula first job hanggang kung nasaan na sila ngayon"]],
    ],
    monetization: [
      ["Resume and LinkedIn makeovers", "Resume at LinkedIn makeovers"],
      ["1:1 career coaching", "1:1 career coaching"],
      ["Interview-prep workshops", "Interview-prep workshops"],
      ["Company training on hiring and onboarding", "Company training sa hiring at onboarding"],
    ],
    demand: [
      "Job-hunting and salary questions spike every graduation season and every bonus season.",
      "Laging trending ang job hunting at salary questions — every graduation season at every bonus season.",
    ],
    demandScore: 8,
  },
  {
    id: "food",
    match: /\b(cook\w*|bak(e|es|ing|er|ers|ery)|food\w*|recipes?|luto|pagluluto|kusina|kitchen|pastry|pastries|cakes?|coffee|cafes?|café|restaurants?|carinderia|meal prep|kakanin)\b/,
    topic: ["home cooking and baking", "home cooking at baking"],
    theme: ["food business", "food business"],
    industry: "Food",
    audience: ["home cooks and home bakers", "home cooks at home bakers"],
    result: ["cook with confidence and sell what they make", "magluto nang confident at mabenta ang ginagawa nila"],
    method: ["tested recipes and simple food-business systems", "tested na recipes at simple na food-business systems"],
    pillars: [
      [["Tested recipes", "Tested recipes"], ["Exact measurements and budget-friendly swaps", "Exact na sukat at budget-friendly na alternatives"]],
      [["Kitchen skills", "Kitchen skills"], ["Techniques that make every dish better", "Techniques na nagpapasarap sa bawat luto"]],
      [["Food business basics", "Food business basics"], ["Costing, pricing and selling from home", "Costing, pricing at pagbebenta from home"]],
      [["Behind the kitchen", "Behind the kitchen"], ["Prep days, fails and what happens before the photo", "Prep days, fails at ano ang nangyayari bago ang photo"]],
      [["Food stories", "Food stories"], ["The people, places and memories behind the food", "Ang mga tao, lugar at alaala sa likod ng pagkain"]],
    ],
    monetization: [
      ["Recipe e-books and costing templates", "Recipe e-books at costing templates"],
      ["Cooking or baking classes", "Cooking o baking classes"],
      ["Home-based food orders", "Home-based na food orders"],
      ["Partnerships with kitchen and food brands", "Partnerships sa kitchen at food brands"],
    ],
    demand: [
      "Food content is evergreen in the Philippines, and home-based food businesses keep asking about pricing and costing.",
      "Evergreen ang food content sa Pilipinas — at laging tanong ng home-based food businesses ang pricing at costing.",
    ],
    demandScore: 8,
  },
  {
    id: "fitness",
    match: /\b(fitness|gym|workouts?|exercis\w*|runners?|marathons?|yoga|weight loss|diet\w*|nutrition|(?<!mental )health(?:y|ier|iest)?|wellness|pilates|calisthenics|hiking|lifting)\b/,
    topic: ["fitness and healthy living", "fitness at healthy living"],
    theme: ["fitness", "fitness"],
    industry: "Health & fitness",
    audience: ["busy professionals", "busy professionals"],
    result: ["get fit and stay consistent on a busy schedule", "maging fit at consistent kahit busy"],
    method: ["short workouts and realistic eating habits", "short workouts at realistic na eating habits"],
    pillars: [
      [["Workouts that fit", "Workouts that fit"], ["Short routines for busy days, at home or at the gym", "Short routines para sa busy days — sa bahay o sa gym"]],
      [["Eating real food", "Eating real food"], ["Filipino meals made healthier — no crash diets", "Pinoy meals na mas healthy — walang crash diet"]],
      [["Consistency habits", "Consistency habits"], ["How to keep going when motivation is gone", "Paano magtuloy kahit wala nang motivation"]],
      [["Fitness myths", "Fitness myths"], ["Common advice that doesn't work — and what does", "Mga common na advice na hindi gumagana — at ano ang gumagana"]],
      [["Progress stories", "Progress stories"], ["Real transformations and honest setbacks", "Totoong transformations at honest na setbacks"]],
    ],
    monetization: [
      ["Online coaching programs", "Online coaching programs"],
      ["Workout and meal plans", "Workout at meal plans"],
      ["Group classes or challenges", "Group classes o challenges"],
      ["Partnerships with fitness and food brands", "Partnerships sa fitness at food brands"],
    ],
    demand: [
      "Health goals come back every January and every summer, and people want plans that fit Filipino food and schedules.",
      "Bumabalik ang health goals every January at every summer — gusto ng mga tao ng plan na swak sa Pinoy food at schedule.",
    ],
    demandScore: 8,
    risk: [
      "Health advice needs care — share your experience and refer medical questions to professionals.",
      "Kailangan ng ingat sa health advice — i-share ang experience mo at i-refer sa professionals ang medical na tanong.",
    ],
  },
  {
    id: "parenting",
    match: /\b(parent\w*|moms?|mommy|mommies|nanay|tatay|dads?|father\w*|mother\w*|kids?|anak|toddlers?|homeschool\w*|family life|pamilya|bab(y|ies)|pregnan\w*)\b/,
    topic: ["parenting", "parenting"],
    theme: ["parenting", "parenting"],
    industry: "Parenting & family",
    audience: ["first-time parents", "first-time parents"],
    result: ["raise their kids with less stress and more confidence", "magpalaki ng anak nang mas kaunti ang stress at mas confident"],
    method: ["practical routines and honest parenting stories", "practical na routines at honest na parenting stories"],
    pillars: [
      [["Family routines", "Family routines"], ["Sleep, meals and daily routines that actually work", "Tulog, kain at daily routines na talagang gumagana"]],
      [["Raising good kids", "Raising good kids"], ["Discipline, values and emotions — gently and practically", "Disiplina, values at emotions — gentle pero practical"]],
      [["Family money & time", "Family money & time"], ["Budgeting and time for busy families", "Budget at oras para sa busy na pamilya"]],
      [["Real parent life", "Real parent life"], ["The messy, funny, honest side of parenting", "Ang magulo, nakakatawa at honest na side ng parenting"]],
      [["Parent questions", "Parent questions"], ["Answering what parents ask every week", "Sinasagot ang mga tanong ng parents every week"]],
    ],
    monetization: [
      ["Parenting guides and printable routines", "Parenting guides at printable routines"],
      ["Workshops for parents", "Workshops para sa parents"],
      ["Partnerships with family brands", "Partnerships sa family brands"],
      ["Paid parent community", "Paid na parent community"],
    ],
    demand: [
      "New parents search for answers late at night, and they trust other parents more than experts.",
      "Gabi-gabi naghahanap ng sagot ang mga bagong parents — at mas pinagkakatiwalaan nila ang kapwa parents.",
    ],
    demandScore: 7,
    risk: [
      "Your kids' privacy matters — decide early what you'll never show.",
      "Mahalaga ang privacy ng mga anak mo — magdesisyon agad kung ano ang hindi mo ipapakita.",
    ],
  },
  {
    id: "tech",
    match: /\b(tech|technology|programming|coding|developers?|software|web dev\w*|ai|artificial intelligence|chatgpt|automation|no-?code|excel|spreadsheets?|google sheets|data|analytics|productivity apps?|notion)\b/,
    topic: ["AI tools and tech skills", "AI tools at tech skills"],
    theme: ["AI tools", "AI tools"],
    industry: "Technology",
    audience: ["professionals who want to work smarter", "professionals na gustong mag-work smarter"],
    result: ["save hours every week and stay relevant at work", "makatipid ng oras every week at manatiling relevant sa trabaho"],
    method: ["practical tutorials on tools they already use", "practical na tutorials sa tools na gamit na nila"],
    pillars: [
      [["Tool tutorials", "Tool tutorials"], ["Step-by-step guides for tools people use every day", "Step-by-step na guides sa tools na araw-araw ginagamit"]],
      [["AI at work", "AI at work"], ["Real workflows where AI saves time — and where it doesn't", "Totoong workflows kung saan nakakatipid ang AI — at kung saan hindi"]],
      [["Automation wins", "Automation wins"], ["Small automations that remove boring work", "Maliliit na automation na nag-aalis ng boring na trabaho"]],
      [["Tech career paths", "Tech career paths"], ["Skills, certificates and how people break into tech", "Skills, certificates at paano nakakapasok sa tech"]],
      [["Build in public", "Build in public"], ["What I'm building, testing and learning", "Ano ang binubuo, tine-test at natututunan ko"]],
    ],
    monetization: [
      ["Templates and automation packs", "Templates at automation packs"],
      ["Corporate training and workshops", "Corporate training at workshops"],
      ["Freelance or consulting projects", "Freelance o consulting projects"],
      ["Online course", "Online course"],
    ],
    demand: [
      "AI changed almost every desk job in two years — people want someone who shows them how, in plain language.",
      "Binago ng AI ang halos lahat ng desk job — gusto ng mga tao ng magtuturo kung paano, in simple terms.",
    ],
    demandScore: 9,
  },
  {
    id: "design",
    match: /\b(design\w*|graphics?|canva|figma|photograph\w*|photos?|illustrat\w*|arts?|drawing|ui|ux|video edit\w*|videograph\w*|creatives?|editing)\b/,
    topic: ["design and visual skills", "design at visual skills"],
    theme: ["design", "design"],
    industry: "Design & creative",
    audience: ["aspiring designers and creatives", "aspiring designers at creatives"],
    result: ["build a portfolio and get paid for creative work", "makabuo ng portfolio at mabayaran sa creative work"],
    method: ["practical design lessons and real client projects", "practical na design lessons at totoong client projects"],
    pillars: [
      [["Design lessons", "Design lessons"], ["Principles and quick fixes that make any design better", "Principles at quick fixes na nagpapaganda sa kahit anong design"]],
      [["Tools & workflows", "Tools & workflows"], ["Canva, Figma and editing workflows, step by step", "Canva, Figma at editing workflows — step by step"]],
      [["Portfolio & pricing", "Portfolio & pricing"], ["Building a portfolio and pricing creative work", "Pagbuo ng portfolio at pag-price ng creative work"]],
      [["Redesigns", "Redesigns"], ["Before-and-after redesigns with the reasoning", "Before-and-after na redesigns kasama ang reasoning"]],
      [["Creative process", "Creative process"], ["Behind the scenes of real projects", "Behind the scenes ng totoong projects"]],
    ],
    monetization: [
      ["Design services for businesses", "Design services para sa businesses"],
      ["Templates and presets", "Templates at presets"],
      ["Portfolio reviews", "Portfolio reviews"],
      ["Workshops and courses", "Workshops at courses"],
    ],
    demand: [
      "Businesses need visuals every day, and new designers want someone who teaches the business side too.",
      "Araw-araw kailangan ng businesses ng visuals — at gusto ng bagong designers ng nagtuturo pati ng business side.",
    ],
    demandScore: 7,
  },
  {
    id: "realestate",
    match: /\b(real estate|propert(y|ies)|condos?|condominium|house and lot|lot for sale|housing|rentals?|brokers?|brokerage)\b/,
    topic: ["real estate", "real estate"],
    theme: ["property", "property"],
    industry: "Real estate",
    audience: ["first-time home buyers", "first-time home buyers"],
    result: ["buy their first property without costly mistakes", "makabili ng unang property nang walang mahal na pagkakamali"],
    method: ["plain-language guides and honest computations", "simple na guides at honest na computations"],
    pillars: [
      [["Buying 101", "Buying 101"], ["Steps, documents and financing explained simply", "Steps, documents at financing — explained nang simple"]],
      [["Real computations", "Real computations"], ["Monthly payments, fees and hidden costs, computed honestly", "Monthly payments, fees at hidden costs — honest na computation"]],
      [["Property red flags", "Property red flags"], ["Mistakes and scams to avoid", "Mga pagkakamali at scams na dapat iwasan"]],
      [["Market takes", "Market takes"], ["What's happening in the market and what it means for buyers", "Ano ang nangyayari sa market at ano ang ibig sabihin nito sa buyers"]],
      [["Buyer journeys", "Buyer journeys"], ["Real buyer stories — from inquiry to keys", "Totoong buyer stories — mula inquiry hanggang susi"]],
    ],
    monetization: [
      ["Brokerage commissions", "Brokerage commissions"],
      ["Paid consultations", "Paid consultations"],
      ["Buyer's guide e-book", "Buyer's guide e-book"],
      ["Developer partnerships", "Developer partnerships"],
    ],
    demand: [
      "Buying property is a once-in-a-lifetime decision — people research for months before they call anyone.",
      "Once-in-a-lifetime decision ang pagbili ng property — ilang buwan nagre-research ang mga tao bago tumawag kahit kanino.",
    ],
    demandScore: 7,
    risk: [
      "Trust is everything here — never oversell a project, show your computations and disclose commissions.",
      "Trust ang lahat dito — huwag i-oversell ang project, ipakita ang computations at i-disclose ang commission.",
    ],
  },
  {
    id: "ofw",
    match: /\b(ofws?|abroad|overseas|migrat\w*|immigra\w*|visas?|nclex|ielts|seafar\w*|seaman|canada|australia|dubai|middle east)\b/,
    topic: ["working abroad", "working abroad"],
    theme: ["working abroad", "abroad"],
    industry: "Migration & overseas work",
    audience: ["Filipinos planning to work abroad", "mga Pinoy na planong mag-abroad"],
    result: ["get abroad the legit way and build savings for coming home", "makapag-abroad sa legit na paraan at makapag-ipon para sa pag-uwi"],
    method: ["step-by-step guides from someone who's done it", "step-by-step na guides mula sa taong nakagawa na nito"],
    pillars: [
      [["Getting there", "Getting there"], ["Requirements, exams and processing, step by step", "Requirements, exams at processing — step by step"]],
      [["Life abroad", "Life abroad"], ["The honest daily life — costs, work, homesickness", "Ang honest na daily life — gastos, trabaho, homesickness"]],
      [["OFW money", "OFW money"], ["Remittances, saving and investing for the future", "Remittances, ipon at investing para sa future"]],
      [["Scam alerts", "Scam alerts"], ["Red flags in agencies and offers", "Red flags sa agencies at offers"]],
      [["OFW stories", "OFW stories"], ["Real journeys of people who made the move", "Totoong journey ng mga taong nakaalis na"]],
    ],
    monetization: [
      ["Consultations on requirements and processing", "Consultations sa requirements at processing"],
      ["Application guides and checklists", "Application guides at checklists"],
      ["Disclosed partnerships with remittance and banking apps", "Partnerships sa remittance at banking apps (with disclosure)"],
      ["Community for applicants", "Community para sa applicants"],
    ],
    demand: [
      "Millions of Filipino families have someone abroad — and every applicant wants a trusted guide.",
      "Milyon-milyong pamilyang Pinoy ang may kamag-anak abroad — at bawat applicant, naghahanap ng trusted na guide.",
    ],
    demandScore: 9,
    risk: [
      "Processes change by country and year — date your advice and never promise placement.",
      "Nag-iiba ang proseso per bansa at per taon — lagyan ng date ang advice mo at huwag mag-promise ng placement.",
    ],
  },
  {
    id: "education",
    match: /\b(teach\w*|tutor\w*|education|schools?|students?|study|studying|board exams?|reviewers?|let exam|licensure|college|online class\w*|esl|english)\b/,
    topic: ["learning and study skills", "learning at study skills"],
    theme: ["studying", "pag-aaral"],
    industry: "Education",
    audience: ["students and board-exam reviewees", "students at board-exam reviewees"],
    result: ["study smarter and pass the exams that matter", "mag-aral nang mas matalino at pumasa sa mga exam na mahalaga"],
    method: ["proven study techniques and clear explanations", "proven na study techniques at malinaw na explanations"],
    pillars: [
      [["Study systems", "Study systems"], ["Techniques and schedules that make studying stick", "Techniques at schedules para tumatak ang inaaral"]],
      [["Explained simply", "Explained simply"], ["Hard topics broken down in minutes", "Mahihirap na topics, hinimay in minutes"]],
      [["Exam strategy", "Exam strategy"], ["Reviewing, test-taking and handling pressure", "Reviewing, test-taking at pag-handle ng pressure"]],
      [["Student life", "Student life"], ["Balancing school, money and mental health", "Balanse sa school, pera at mental health"]],
      [["Passer stories", "Passer stories"], ["Real stories from students who made it", "Totoong kwento ng mga pumasa"]],
    ],
    monetization: [
      ["Tutoring or review classes", "Tutoring o review classes"],
      ["Reviewers and study guides", "Reviewers at study guides"],
      ["Online course", "Online course"],
      ["School partnerships", "School partnerships"],
    ],
    demand: [
      "Every exam season brings a new wave of students looking for reviewers and study tips.",
      "Every exam season, may bagong batch ng students na naghahanap ng reviewers at study tips.",
    ],
    demandScore: 8,
  },
  {
    id: "travel",
    match: /\b(travel\w*|trips?|backpack\w*|beach\w*|islands?|tours?|gala|lakwatsa|flights?|hotels?|seat sales?)\b/,
    topic: ["budget travel", "budget travel"],
    theme: ["travel", "travel"],
    industry: "Travel",
    audience: ["Filipinos who want to travel on a budget", "mga Pinoy na gustong mag-travel nang tipid"],
    result: ["travel more often without draining their savings", "mas madalas mag-travel nang hindi nauubos ang ipon"],
    method: ["real itineraries with real costs", "totoong itineraries na may totoong gastos"],
    pillars: [
      [["Itineraries with costs", "Itineraries with costs"], ["Day-by-day plans with the real total", "Day-by-day na plan kasama ang totoong total"]],
      [["Travel hacks", "Travel hacks"], ["Seat sales, visas and packing that save money", "Seat sales, visas at packing na nakakatipid"]],
      [["Hidden spots", "Hidden spots"], ["Places worth the trip, local and abroad", "Mga lugar na sulit puntahan — local at abroad"]],
      [["Travel mistakes", "Travel mistakes"], ["What went wrong so you don't repeat it", "Ano ang pumalpak para hindi mo na maulit"]],
      [["Travel stories", "Travel stories"], ["The people and moments behind the photos", "Ang mga tao at moments sa likod ng photos"]],
    ],
    monetization: [
      ["Itinerary guides", "Itinerary guides"],
      ["Disclosed affiliate bookings", "Affiliate bookings (with disclosure)"],
      ["Tourism and hotel partnerships", "Tourism at hotel partnerships"],
      ["Organised group trips", "Organized na group trips"],
    ],
    demand: [
      "Seat sales and long weekends keep Filipinos planning trips all year — and they want real costs, not just pretty photos.",
      "Dahil sa seat sales at long weekends, buong taon nagpaplano ng trip ang mga Pinoy — at gusto nila ng totoong gastos, hindi lang magandang photos.",
    ],
    demandScore: 7,
    risk: [
      "Travel content is crowded — your angle (budget, family, solo, food) has to be obvious in every post.",
      "Siksikan ang travel content — dapat obvious ang angle mo (budget, family, solo, food) sa bawat post.",
    ],
  },
  {
    id: "beauty",
    match: /\b(beauty|skincare|skin care|makeup|make-up|fashion|style|styling|outfits?|ootd|hair\w*|nails?|thrift\w*|ukay)\b/,
    topic: ["beauty and style", "beauty at style"],
    theme: ["beauty", "beauty"],
    industry: "Beauty & fashion",
    audience: ["young women on a budget", "young women na may budget"],
    result: ["look and feel their best without overspending", "gumanda at maging confident nang hindi gumagastos nang malaki"],
    method: ["honest reviews and affordable routines", "honest na reviews at affordable na routines"],
    pillars: [
      [["Affordable routines", "Affordable routines"], ["Skincare and makeup routines that fit a budget", "Skincare at makeup routines na pasok sa budget"]],
      [["Honest reviews", "Honest reviews"], ["Products tested for weeks, not hours", "Products na tinest nang ilang linggo, hindi ilang oras"]],
      [["Style on a budget", "Style on a budget"], ["Outfits, ukay finds and building a wardrobe", "Outfits, ukay finds at pagbuo ng wardrobe"]],
      [["Beauty myths", "Beauty myths"], ["Popular tips that don't work — and why", "Mga sikat na tips na hindi gumagana — at bakit"]],
      [["Glow-up stories", "Glow-up stories"], ["Real routines and results, no filters", "Totoong routines at results — walang filter"]],
    ],
    monetization: [
      ["Disclosed brand partnerships and affiliate links", "Brand partnerships at affiliate links (with disclosure)"],
      ["Styling or skincare consultations", "Styling o skincare consultations"],
      ["Your own product line, later", "Sariling product line — later"],
      ["Workshops", "Workshops"],
    ],
    demand: [
      "Beauty is one of the biggest categories on TikTok Shop and Shopee — people want honest reviews before they buy.",
      "Isa sa pinakamalaking category ang beauty sa TikTok Shop at Shopee — gusto ng mga tao ng honest reviews bago bumili.",
    ],
    demandScore: 8,
  },
  {
    id: "growth",
    match: /\b(mental health|self-?growth|self-?improvement|personal develop\w*|mindset|habits?|journaling|faith|christian|spiritual\w*|motivation|productivity|burnout|anxiety|self-?care|books?|reading)\b/,
    topic: ["self-growth", "self-growth"],
    theme: ["self-growth", "self-growth"],
    industry: "Personal development",
    audience: ["young professionals who feel stuck", "young professionals na feeling stuck"],
    result: ["build better habits and feel in control of their life", "makabuo ng better habits at maramdamang hawak nila ang buhay nila"],
    method: ["small daily habits and honest reflection", "maliliit na daily habits at honest na reflection"],
    pillars: [
      [["Habits & routines", "Habits & routines"], ["Small daily systems that compound", "Maliliit na daily systems na nagco-compound"]],
      [["Mindset shifts", "Mindset shifts"], ["Beliefs that change how you work and live", "Mga paniniwalang nagbabago sa paraan ng trabaho at buhay"]],
      [["Hard seasons", "Hard seasons"], ["Burnout, anxiety and getting through — honestly", "Burnout, anxiety at paano nakakalampas — honestly"]],
      [["Books & lessons", "Books & lessons"], ["Takeaways from books, mentors and mistakes", "Takeaways mula sa books, mentors at mga pagkakamali"]],
      [["My growth journal", "My growth journal"], ["What I'm working on and what's changing", "Ano ang ginagawa ko at ano ang nagbabago"]],
    ],
    monetization: [
      ["Coaching", "Coaching"],
      ["Journals, planners and templates", "Journals, planners at templates"],
      ["Workshops and talks", "Workshops at talks"],
      ["Paid community", "Paid na community"],
    ],
    demand: [
      "Burnout and feeling stuck are everyday conversations now, especially among young professionals.",
      "Araw-araw nang pinag-uusapan ang burnout at pagiging stuck, lalo na sa mga young professional.",
    ],
    demandScore: 7,
    risk: [
      "It's easy to sound generic here — anchor every post in your own specific story.",
      "Madaling maging generic dito — i-angkla ang bawat post sa sarili mong specific na kwento.",
    ],
  },
  {
    id: "business",
    match: /\b(negosyo|small business\w*|entrepreneur\w*|msmes?|sari-?sari|franchis\w*|startups?|business owners?|smes?|business\w*)\b/,
    topic: ["small business", "negosyo"],
    theme: ["negosyo", "negosyo"],
    industry: "Small business",
    audience: ["first-time business owners", "first-time business owners"],
    result: ["run a profitable business that doesn't depend on them for everything", "magpatakbo ng profitable na negosyo na hindi umaasa sa kanila sa lahat"],
    method: ["simple business systems and real numbers", "simple na business systems at totoong numbers"],
    pillars: [
      [["Negosyo basics", "Negosyo basics"], ["Starting right: costing, permits and first customers", "Tamang simula: costing, permits at unang customers"]],
      [["Systems & SOPs", "Systems & SOPs"], ["How to stop doing everything yourself", "Paano tumigil sa paggawa ng lahat nang mag-isa"]],
      [["Numbers that matter", "Numbers that matter"], ["Profit, cash flow and pricing, explained simply", "Profit, cash flow at pricing — explained nang simple"]],
      [["Growth moves", "Growth moves"], ["Marketing, hiring and expansion, step by step", "Marketing, hiring at expansion — step by step"]],
      [["Owner stories", "Owner stories"], ["Real wins, losses and lessons from running a business", "Totoong panalo, talo at lessons sa pagpapatakbo ng negosyo"]],
    ],
    monetization: [
      ["Business coaching or consulting", "Business coaching o consulting"],
      ["Costing, SOP and hiring templates", "Templates: costing, SOP at hiring"],
      ["Workshops for MSMEs", "Workshops para sa MSMEs"],
      ["Paid mastermind community", "Paid na mastermind community"],
    ],
    demand: [
      "Almost every Filipino wants a negosyo someday — and most first-time owners learn the hard way.",
      "Halos lahat ng Pinoy, gusto ng negosyo someday — at karamihan ng first-time owners, natututo the hard way.",
    ],
    demandScore: 8,
  },
  {
    id: "leadership",
    match: /\b(leadership|leaders?|manag(er|ers|ement|ing)|teams?|people management|supervis\w*|(?<!pop )culture|operations|sops?)\b/,
    topic: ["leadership", "leadership"],
    theme: ["leadership", "leadership"],
    industry: "Leadership & management",
    audience: ["new managers", "new managers"],
    result: ["lead a team that performs without micromanaging", "mag-lead ng team na nagpe-perform nang hindi nagma-micromanage"],
    method: ["practical leadership frameworks from real teams", "practical na leadership frameworks mula sa totoong teams"],
    pillars: [
      [["First-time manager", "First-time manager"], ["The skills nobody teaches when you get promoted", "Mga skills na hindi itinuturo pag na-promote ka"]],
      [["Hard conversations", "Hard conversations"], ["Feedback, conflict and performance issues, handled well", "Feedback, conflict at performance issues — na-handle nang maayos"]],
      [["Building teams", "Building teams"], ["Hiring, onboarding and culture", "Hiring, onboarding at culture"]],
      [["Leading yourself", "Leading yourself"], ["Time, energy and decisions as a leader", "Oras, energy at decisions bilang leader"]],
      [["Leadership lessons", "Leadership lessons"], ["What I got right and wrong leading real teams", "Ano ang tama at mali ko sa pag-lead ng totoong teams"]],
    ],
    monetization: [
      ["Leadership coaching", "Leadership coaching"],
      ["Corporate training", "Corporate training"],
      ["Speaking engagements", "Speaking engagements"],
      ["Manager toolkits", "Manager toolkits"],
    ],
    demand: [
      "Most managers were promoted for being good at the job, not for leading — and they're quietly looking for help.",
      "Karamihan ng managers, na-promote dahil magaling sa trabaho, hindi sa pag-lead — at tahimik silang naghahanap ng tulong.",
    ],
    demandScore: 7,
  },
  {
    id: "sales",
    match: /\b(sales|closing|negotiat\w*|insurance agents?|financial advisors?|network marketing|b2b|prospecting)\b/,
    topic: ["sales", "sales"],
    theme: ["sales", "sales"],
    industry: "Sales",
    audience: ["new sales professionals", "new sales professionals"],
    result: ["close more deals without feeling pushy", "mag-close ng mas maraming deals nang hindi nagiging pushy"],
    method: ["honest, repeatable sales conversations", "honest at repeatable na sales conversations"],
    pillars: [
      [["Prospecting", "Prospecting"], ["Finding and starting conversations with the right people", "Paghanap at pagsimula ng usapan sa tamang tao"]],
      [["Closing without pressure", "Closing without pressure"], ["Scripts and objection handling that feel human", "Scripts at objection handling na natural"]],
      [["Sales mindset", "Sales mindset"], ["Rejection, targets and staying consistent", "Rejection, targets at pagiging consistent"]],
      [["Deal breakdowns", "Deal breakdowns"], ["Real deals — what worked and what didn't", "Totoong deals — ano ang gumana at hindi"]],
      [["Sales life", "Sales life"], ["The honest daily life of selling for a living", "Ang honest na daily life ng pagbebenta for a living"]],
    ],
    monetization: [
      ["Sales coaching", "Sales coaching"],
      ["Team training", "Team training"],
      ["Scripts and templates", "Scripts at templates"],
      ["Speaking at sales events", "Speaking sa sales events"],
    ],
    demand: [
      "Every business needs people who can sell, and most salespeople were never properly trained.",
      "Kailangan ng bawat business ng marunong magbenta — at karamihan ng salespeople, hindi na-train nang maayos.",
    ],
    demandScore: 7,
  },
  {
    id: "healthcare",
    match: /\b(nurs\w*|medtech|medical|doctors?|pharmac\w*|caregiv\w*|healthcare|hospitals?|physical therap\w*|midwi\w*)\b/,
    topic: ["healthcare careers", "healthcare careers"],
    theme: ["healthcare careers", "healthcare careers"],
    industry: "Healthcare",
    audience: ["nursing students and new nurses", "nursing students at new nurses"],
    result: ["pass their boards and build a stable healthcare career", "pumasa sa boards at makabuo ng stable na healthcare career"],
    method: ["real-world tips from the hospital floor", "real-world tips mula sa hospital floor"],
    pillars: [
      [["Board exam prep", "Board exam prep"], ["Reviewers, schedules and test-taking strategy", "Reviewers, schedules at test-taking strategy"]],
      [["Life on duty", "Life on duty"], ["What hospital work is really like", "Ano talaga ang trabaho sa hospital"]],
      [["Career paths", "Career paths"], ["Local vs abroad, specialisations and next steps", "Local vs abroad, specializations at next steps"]],
      [["Health explained", "Health explained"], ["Common health topics in plain language", "Common na health topics sa simpleng salita"]],
      [["Shift stories", "Shift stories"], ["Real shifts and lessons, with patients anonymised", "Totoong shifts at lessons — anonymous ang patients"]],
    ],
    monetization: [
      ["Review classes and reviewers", "Review classes at reviewers"],
      ["Mentoring for applicants going abroad", "Mentoring para sa applicants na mag-a-abroad"],
      ["Health brand partnerships", "Health brand partnerships"],
      ["Workshops for schools", "Workshops para sa schools"],
    ],
    demand: [
      "Healthcare is one of the biggest career paths in the Philippines, and every batch wants guidance.",
      "Isa sa pinakamalaking career path sa Pilipinas ang healthcare — at bawat batch, naghahanap ng guidance.",
    ],
    demandScore: 8,
    risk: [
      "Patient privacy comes first — never share identifiable cases, and keep medical advice general.",
      "Una ang privacy ng patients — huwag mag-share ng identifiable na cases at panatilihing general ang medical advice.",
    ],
  },
  {
    id: "plants",
    match: /\b(plants?|plantita|plantito|gardening|gardens?|halaman|farming|farms?|agri\w*|urban farming|succulents?|hydroponic\w*)\b/,
    topic: ["plants and home gardening", "plants at home gardening"],
    theme: ["plants", "halaman"],
    industry: "Gardening & agriculture",
    audience: ["plant lovers with small spaces", "plant lovers na maliit ang space"],
    result: ["grow healthy plants and food even in small spaces", "makapagtanim ng healthy na halaman at pagkain kahit maliit ang space"],
    method: ["simple, tested growing guides", "simple at tested na growing guides"],
    pillars: [
      [["Plant care basics", "Plant care basics"], ["Light, water and soil — the basics done right", "Araw, tubig at lupa — ang basics na tama"]],
      [["Grow your own food", "Grow your own food"], ["Herbs and vegetables for small spaces", "Herbs at gulay para sa maliit na space"]],
      [["Plant rescue", "Plant rescue"], ["Fixing dying plants and common problems", "Pagsalba sa namamatay na halaman at common na problema"]],
      [["Plant finds", "Plant finds"], ["Where to buy, what's worth it and what to avoid", "Saan bibili, ano ang sulit at ano ang iiwasan"]],
      [["Garden diary", "Garden diary"], ["What's growing, what failed and what's next", "Ano ang lumalaki, ano ang namatay at ano ang susunod"]],
    ],
    monetization: [
      ["Selling plants and seedlings", "Pagbebenta ng plants at seedlings"],
      ["Gardening workshops", "Gardening workshops"],
      ["Plant-care guides", "Plant-care guides"],
      ["Partnerships with garden brands", "Partnerships sa garden brands"],
    ],
    demand: [
      "Plant parenting and urban gardening stayed popular long after the pandemic.",
      "Nanatiling popular ang plant parenting at urban gardening kahit tapos na ang pandemic.",
    ],
    demandScore: 6,
  },
  {
    id: "gaming",
    match: /\b(gaming|gamers?|games?|esports?|mobile legends|valorant|dota|streamers?|twitch)\b/,
    topic: ["gaming", "gaming"],
    theme: ["gaming", "gaming"],
    industry: "Gaming",
    audience: ["mobile gamers", "mobile gamers"],
    result: ["get better at their games and turn gaming into more than a hobby", "gumaling sa games nila at gawing higit pa sa hobby ang gaming"],
    method: ["guides, reviews and honest streams", "guides, reviews at honest na streams"],
    pillars: [
      [["Guides & tips", "Guides & tips"], ["Builds, strategies and rank-up tips", "Builds, strategies at rank-up tips"]],
      [["Updates & reviews", "Updates & reviews"], ["Patches, new games and honest reviews", "Patches, bagong games at honest na reviews"]],
      [["Budget setups", "Budget setups"], ["Phones, PCs and gear that are worth it", "Phones, PCs at gear na sulit"]],
      [["Gaming culture", "Gaming culture"], ["Tournaments, community and the scene", "Tournaments, community at ang scene"]],
      [["Stream highlights", "Stream highlights"], ["The best, worst and funniest moments", "Ang best, worst at pinakanakakatawang moments"]],
    ],
    monetization: [
      ["Streaming support and donations", "Streaming support at donations"],
      ["Gear sponsorships", "Gear sponsorships"],
      ["Coaching for players", "Coaching para sa players"],
      ["Affiliate links for gear (disclosed)", "Affiliate links sa gear (with disclosure)"],
    ],
    demand: [
      "Mobile gaming is huge in the Philippines, and players constantly look for guides and honest reviews.",
      "Sobrang laki ng mobile gaming sa Pilipinas — at laging naghahanap ang players ng guides at honest na reviews.",
    ],
    demandScore: 7,
    risk: [
      "Gaming audiences are loyal but young — income comes slower unless you add a skill or review angle.",
      "Loyal pero bata ang gaming audience — mas mabagal ang kita unless may skill o review angle ka.",
    ],
  },
  {
    id: "entertainment",
    match: /\b(k-?dramas?|kdramas?|k-?pop|anime|movies?|films?|netflix|pop culture|showbiz|music|singing|guitar|piano|songwrit\w*|musicians?|concerts?)\b/,
    topic: ["pop culture", "pop culture"],
    theme: ["pop culture", "pop culture"],
    industry: "Entertainment & media",
    audience: ["fans who want more than recaps", "fans na gusto ng higit pa sa recaps"],
    result: ["get smarter takes and recommendations on what they love", "makakuha ng mas matalinong takes at recommendations sa mga gusto nila"],
    method: ["sharp reviews, breakdowns and recommendations", "matalas na reviews, breakdowns at recommendations"],
    pillars: [
      [["Reviews & takes", "Reviews & takes"], ["Honest opinions on what's new", "Honest na opinion sa mga bago"]],
      [["Breakdowns", "Breakdowns"], ["Why a scene, song or story works", "Bakit gumagana ang isang scene, kanta o kwento"]],
      [["Recommendations", "Recommendations"], ["What to watch or listen to next — and who it's for", "Ano ang susunod na panoorin o pakinggan — at para kanino"]],
      [["Fan culture", "Fan culture"], ["Community, events and the fun side of being a fan", "Community, events at ang saya ng pagiging fan"]],
      [["Life lessons from stories", "Life lessons from stories"], ["What the stories we love teach about real life", "Ano ang itinuturo ng mga paborito nating kwento tungkol sa totoong buhay"]],
    ],
    monetization: [
      ["Brand and streaming partnerships", "Brand at streaming partnerships"],
      ["Event and merch collaborations", "Event at merch collaborations"],
      ["Paid community or newsletter", "Paid na community o newsletter"],
      ["Affiliate links (disclosed)", "Affiliate links (with disclosure)"],
    ],
    demand: [
      "Filipino fans are among the most active online — they look for takes, not just summaries.",
      "Isa ang Pinoy fans sa pinaka-active online — naghahanap sila ng takes, hindi lang summaries.",
    ],
    demandScore: 7,
    risk: [
      "Entertainment content is hit-driven — tie it to a lesson or your expertise so it can earn beyond views.",
      "Hit-driven ang entertainment content — i-connect sa lesson o expertise mo para kumita beyond views.",
    ],
  },
  {
    id: "pets",
    match: /\b(pets?|dogs?|cats?|aso|pusa|fur ?bab(y|ies)|fur ?parents?|pet care)\b/,
    topic: ["pet care", "pet care"],
    theme: ["pet care", "pet care"],
    industry: "Pets",
    audience: ["first-time fur parents", "first-time fur parents"],
    result: ["raise healthy, happy pets without costly mistakes", "mag-alaga ng healthy at masayang pets nang walang mahal na pagkakamali"],
    method: ["practical care routines and honest product reviews", "practical na care routines at honest na product reviews"],
    pillars: [
      [["Pet care basics", "Pet care basics"], ["Food, grooming and vet visits made simple", "Pagkain, grooming at vet visits — pinasimple"]],
      [["Training & behaviour", "Training & behavior"], ["Fixing common behaviour problems", "Pag-ayos ng common na behavior problems"]],
      [["Honest pet reviews", "Honest pet reviews"], ["Food, toys and products that are worth it", "Pagkain, laruan at products na sulit"]],
      [["Pet budget", "Pet budget"], ["What owning a pet really costs", "Magkano talaga ang mag-alaga ng pet"]],
      [["Pet stories", "Pet stories"], ["Adoptions, rescues and everyday moments", "Adoptions, rescues at everyday moments"]],
    ],
    monetization: [
      ["Pet brand partnerships", "Pet brand partnerships"],
      ["Affiliate links (disclosed)", "Affiliate links (with disclosure)"],
      ["Training or grooming services", "Training o grooming services"],
      ["Care guides", "Care guides"],
    ],
    demand: [
      "Pet ownership keeps growing, and new fur parents search for answers before every vet visit.",
      "Patuloy dumarami ang pet owners — at naghahanap ng sagot ang bagong fur parents bago ang bawat vet visit.",
    ],
    demandScore: 7,
    risk: [
      "Health questions belong to vets — share your experience and point people to professionals.",
      "Sa vet ang health questions — i-share ang experience mo at i-refer ang mga tao sa professionals.",
    ],
  },
]

export const DOMAIN_BY_ID = new Map(NICHE_DOMAINS.map((d) => [d.id, d]))
